### PR TITLE
[ADD] contributing: Add note about avoiding api.v7

### PR DESCRIPTION
**Pull request by lasley**
### Milestone (Odoo version)
- 
v9

### Module(s)
- 
Contributing.mg

### Fixes / new features
- 
This adds a note about avoiding api.v7 except in certain scenarios. Wasn't sure where else it fit, so I put it in idioms.

Admittedly I could be completely off-base here, but this seems like a wise recommendation?

### CODE REVIEW

**Comment by max3903** [comment]
:+1:

**Comment by pedrobaeza** [comment]
:+1:, although I'm intrigued about the Travis error.

**Comment by lasley** [comment]
Looks like it was caused on following merge: https://github.com/OCA/maintainer-tools/commit/22c97c6202f6b49cd93fd389842e940eb26e8497 

According to history: https://travis-ci.org/OCA/maintainer-tools/builds/147765216

Which is even more intriguing because that change was an incredibly simple change in the contrib md. @moylop260 any clue?

**Comment by moylop260** [comment]
@lasley 
Yes, We need more approvals in the following fix: https://github.com/OCA/maintainer-tools/pull/209

**Comment by moylop260** [comment]
Merging...
The travis red is unrelated

**Pull request merged**
