### PR TITLE
[ADD] OCA icon

### PR DESCRIPTION
**Pull request by hbrunn**
how about trying to establish a standard icon (so people are welcome so use something more specific, but can use this as fallback)?

### CODE REVIEW

**Comment by rvalyi** [comment]
:+1: okay for me

**Comment by sebastienbeau** [comment]
:+1:

**Comment by max3903** [comment]
:+1:

**Comment by pedrobaeza** [comment]
I'm not OK with that, because I don't want to see all modules with the same icon that they are not distinguished. One of the goals of the icons and kanban view is to visually diferentiate each element, and with this, the goal fails.

**Comment by max3903** [comment]
@pedrobaeza This is currently the case today (grey cube icon). The OCA logo is still better than the cube and if you don't like it, you can change it ;)

**Comment by pedrobaeza** [comment]
The grey icon is far more neutral...

**Comment by rvalyi** [comment]
what about a grey OCA icon to adjust Pedro's appeal to monochrome monotony?

**Comment by lmignon** [comment]
@rvalyi  :+1:

**Comment by pedrobaeza** [comment]
Let me make a suggestion in a couple of hours.

**Comment by rvalyi** [comment]
that is fine the OCA will certainly find a consensual color to pass over this merge of death. At the same time it's Python and it's Friday, so I propose a convenient poll model to accommodate to the opinion of the subsequent reviewers:
https://www.youtube.com/watch?v=pWS8Mg-JWSg

**Comment by pedrobaeza** [comment]
I have made #53 with my proposal.

**Pull request merged**
