### PR TITLE
update the website adresse

### PR DESCRIPTION
**Pull request by fabienmorin**
The previous domain is expired, update with an address which is still accessible

### CODE REVIEW

**Comment by tafaRU** [comment]
:+1:

**Comment by max3903** [comment]
:+1:

**Comment by elicoidal** [comment]
screenshot from 2016-02-11 12-52-48
The new URL is not a good shot either: there is a warning for expiry.

**Comment by fabienmorin** [comment]
@oca-clabot : I just sent my CLA signed

**Comment by tafaRU** [comment]
> there is a warning for expiry.

@elicoidal you're right, it should be better to avoid it at all then. What do you think about it? cc @fabienmorin

**Comment by dreispt** [comment]
I'm not sure that link should be there in the first place.

**Comment by Yajo** [comment]
:+1:

**Comment by hbrunn** [comment]
how about linking to https://web.archive.org/web/20130111111953/http://insidecoding.wordpress.com/2013/01/07/code-review-guidelines ? Awfully slow, but very bad stuff has to happen to have this link going down

**Comment by fabienmorin** [comment]
not good idea IMO, so slow that it is hard to use, without css, it is web from the 80's and now the address : https://insidecoding.wordpress.com/2013/01/07/code-review-guidelines/
seems to work perfectly without any advertisement.
Regards

**Comment by yvaucher** [comment]
28 days later the url is still valid. Let's fix that dead link. :+1:

**Pull request merged**
