### PR TITLE
Add ES logs instructions.

### PR DESCRIPTION
**Pull request by Yajo**
@Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@mart-e what do you think about this?

**Comment by mart-e** [comment]
You mean to integrate it in the documentation upstream?
Sometimes, I am a bit pessimistic about this. Usually, the people who make the mistakes are the one who do _not_ read the documentation and help.
Well, at least giving a section we can link to could be useful for maintainers.
A section in https://github.com/odoo/odoo/wiki/Contributing ?

**Comment by pedrobaeza** [comment]
Yes, having the link you don't need to copy/paste each time the same text, and you can shut certain mouths saying "This is not explained anywhere"...

**Comment by Yajo** [comment]
I'm personally the PSC of web and website repos in OCA; and it's way very common to have issues with this problem.

Even python programmers which don't understand JS make this failure, not only users. I think it would be very helpful.

Thanks!

**Comment by mart-e** [comment]
Something like this? :wink: 
https://github.com/odoo/odoo/wiki/Contributing#tracebacks
(don't hesitate to correct if needed, I believe you have the access to do so Pedro)

**Comment by Yajo** [comment]
I think this part shouldn't be a code block:

> In Odoo >= 10.0: Go to `Settings > Activate the developer mode (with assets)`.
In Odoo < 10.0: Click on your user menu (top right corner) `> About > Activate the developer mode`.

Other than that, thank you very much!! closing

**Comment by pedrobaeza** [comment]
Great, thanks!

**Pull request closed without merging**
