### PR TITLE
[ADD] gen_addons_table script

### PR DESCRIPTION
**Pull request by sbidoul**
A script that replaces a placeholder in the repository-level README.md with two tables showing the available and unported modules along with their version number and a summary (or name if summary is absent). The placeholder is preserved after running the script.

The placeholder in README.md must be like this (```...``` can be anything):
```
[//]: # (addons)
...
[//]: # (end addons)
```

The syntax for markdown comments comes from http://stackoverflow.com/questions/4823468/store-comments-in-markdown-syntax.

Supersedes https://github.com/OCA/maintainer-quality-tools/pull/239, same code, better repo.

### CODE REVIEW

**Comment by sbidoul** [comment]
@lmignon @moylop260 I added a test as requested in https://github.com/OCA/maintainer-quality-tools/pull/239.

If there is no objection, I'll now work on the mass commit to add the placeholders to all existing README.md on the 8.0 branches. @pedrobaeza you may want to wait until I'm done with this before branching 9.0.

**Comment by pedrobaeza** [comment]
OK, I'l wait to run the script till the mass-commit is done. Thanks for telling.

**Comment by pedrobaeza** [comment]
:+1: Very complete and tested!

**Comment by lmignon** [comment]
:+1: Thank for this work @sbidoul

**Comment by gurneyalex** [comment]
:+1: 

@sbidoul I can help with the mass commit if needed. Ping me on the oca chan on irc if needed. 
Check the oca-clone-everything script for the initial mirroring (in maintainer-tools)

**Comment by sbidoul** [comment]
The mass commit went well, hopefully :sweat:

I pushed a last fix covering the corner case when there are no addons.

@gurneyalex Next step is to setup a bot that periodically runs oca-gen-addons-table on all repos. For that I need help, because I've no ideas how OCA bots are born.

**Comment by moylop260** [comment]
:+1:
Great job
Thanks

You can added a cron in a Dockerfile.
Similar to transifex.
https://github.com/OCA/maintainer-tools/blob/master/Dockerfile-tx-bot

**Comment by guewen** [comment]
This is really nice :+1: Thanks

**Pull request merged**
