### PR TITLE
[REF] never-commit guideline: Add a valid commit

### PR DESCRIPTION
**Pull request by moylop260**
### Milestone (Odoo version)
- >=8.0

### Module(s)
- (guidelines)

### Fixes / new features
- Add a valid commit way

### CODE REVIEW

**Comment by hbrunn** [comment]
@moylop260 I think for new guidelines, we shouldn't refer to the standard (as opposed the legacy) api as *new* by now. I noticed lately that a lot of people who started with 8 as their first version get quite confused when I keep talking about the new api, which is the normal stuff from their point of view.

**Comment by moylop260** [comment]
@hbrunn
You have a good point.
What is `the new` and what is `the old`? <- It is confuse for people who started

Changed!

**Comment by osvalr** [comment]
:+1: for me

**Comment by hbrunn** [comment]
thanks, :+1:

**Pull request merged**
