### PR TITLE
[FIX] allow images in table, and shortcut usage

### PR DESCRIPTION
**Pull request by legalsylvain**
Trivial patch to
- allow images in table.
- allow shortcut on images. (add ``|shortcut|`` before the image.) 

(the regex doesn't match for the time being)

Note I need it to generate this readme file : 
https://github.com/legalsylvain/stock-logistics-barcode/tree/11.0_ADD_mobile_app_picking/mobile_app_picking

Thanks.

### CODE REVIEW

**Comment by legalsylvain** [comment]
(not sure travis is failing due to this PR. Seems broken since some commits)

**Comment by pedrobaeza** [comment]
Please rebase to get a green Travis

**Comment by pedrobaeza** [comment]
@legalsylvain any news about this?

**Comment by legalsylvain** [comment]
Thanks for the review and merge.

**Pull request merged**
