### PR TITLE
[REF] contributing: api.one deprecated

### PR DESCRIPTION
**Pull request by moylop260**
More info here: 
https://github.com/odoo/odoo/pull/8527

### CODE REVIEW

**Comment by pedrobaeza** [comment]
It's too soon to put this until the PR is accepted on v9. Please put here the reference to the PR.

**Comment by moylop260** [comment]
@pedrobaeza 
The PR https://github.com/odoo/odoo/pull/8527 is merged
Official documentation told us
```markdown
 :func:`~.one` often makes the code less clear and behaves in ways
            developers and readers may not expect.
            It is strongly recommended to use :func:`~.multi` and either
            iterate on the ``self`` recordset or ensure that the recordset
            is a single record with :meth:`~openerp.models.Model.ensure_one
```
https://github.com/odoo/odoo/blob/8.0/openerp/api.py#L387

Then we can merge this one in pylint beta messages, for now.

**Comment by nhomar** [comment]
:+1:

**Comment by pedrobaeza** [comment]
Thanks for the info, then :+1:

**Comment by moylop260** [comment]
I dont changed this pr but now there are 27 commits
Do Somebody overwritten with git push or Im wrong?

**Comment by pedrobaeza** [comment]
Yeah, there was a git push -f around by mistake by @elicoidal, so it seems that there's something wrong then. Can you please fix it?

**Comment by pedrobaeza** [comment]
OK, I have fixed by force pushing again and recreating commit history

**Comment by moylop260** [comment]
@pedrobaeza 
I got it
Thank you!

**Pull request merged**
