### PR TITLE
Prevent ImportError by default.

### PR DESCRIPTION
**Pull request by Yajo**
### Fixes / new features

Tired of fixing `ImportError`s [again](https://github.com/OCA/account-financial-reporting/pull/229) and [again](https://github.com/OCA/l10n-spain/pull/255) and [again](https://github.com/OCA/reporting-engine/pull/64) and [again](https://github.com/OCA/reporting-engine/pull/62)...

@Tecnativa

### CODE REVIEW

**Comment by sbidoul** [comment]
I'm not favorable to hide real errors. :-1:

**Comment by Yajo** [comment]
What am I hiding?

**Comment by sbidoul** [comment]
You are transforming potential real bugs (eg a mistyped import statement) into info/debug level logs. 

If you want to solve spurious CI errors due to missing dependencies, let's work on the root cause instead: https://github.com/OCA/maintainer-quality-tools/pull/343 (BTW, I'm willing to work on this during the october sprint)

**Comment by danimaribeiro** [comment]
What's the purpose of loading a module in a inconsistent state?
:-1:

**Comment by lmignon** [comment]
:-1:

**Comment by pedrobaeza** [comment]
You're mixing things: you're not loading modules (they're not even installed), it's Odoo who loads them, at least the Python part. With this, you prevent your server stalls at loading. And it happens when you add a repository to your addons_path for using one of the modules, but you don't want to add the corresponding dependencies for non-installed modules.

Second: I see good all the pip promotion, but there's still a lot of people who don't want or can't use this method, so we shouldn't make this fail in that cases.

**Comment by pedrobaeza** [comment]
Said that, we can lower the try at a deep level for not being so "aggressive" and this masks other programming errors.

**Comment by moylop260** [comment]
@Yajo 
I want understand your point first.

Do you have a real case showing a `ImportError` with `from . import something`?

**Comment by moylop260** [comment]
I understand your point (I saw the url of `again`)

FYI we have a guideline for external dependencies
https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#external-dependencies

You could use it to add this case for template module.

**Comment by moylop260** [comment]
Maybe we can create a new pylint check to validate this case.
Whitelist of allowed imports (internal libraries).
If import not in whitelist then check if there is a try-except-ImportError-logger

**Comment by Yajo** [comment]
I understand the downvotes, but certainly we need a solution for https://github.com/OCA/maintainer-tools/pull/224#issue-178840620. @moylop260's suggestion would be better indeed, however I'm not sure on how to do that...

About pip... I'm not sure on how the pip installing works, but I feel it would harden the task of merging PRs on your production environments, which is something we basically cannot live without. @sbidoul Is there a way to combine both of those needs?

**Comment by sbidoul** [comment]
@Yajo 

>  I feel it would harden the task of merging PRs on your production environments

Merging PR in real world deployment is absolutely necessary indeed. Pip does not make it harder, on the contrary:

- pip has a develop/editable mode to install unreleased code (`pip install -e repo/setup/addon_name`)
- there is [git-aggregator](https://github.com/acsone/git-aggregator) to manage merges in a repeatable manner

It's true it's a change of habitude and it require some learning, but we are very happy we did this change at acsone after several years using buildout. Do good thing is that what you learn with pip is applicable almost everywhere python is used.

**Comment by moylop260** [comment]
FYI I have created the check for pylint-odoo: https://github.com/OCA/pylint-odoo/pull/68

**Comment by Yajo** [comment]
Thanks to both! Closing in favour of the pylint alternative

**Pull request closed without merging**
