### PR TITLE
[ADD] create pr script

### PR DESCRIPTION
**Pull request by moylop260**

### CODE REVIEW

**Comment by gurneyalex** [comment]
@moylop260 why cook our own when we can use https://github.com/github/hub?

**Comment by dreispt** [comment]
@moylop A challenge :sunrise: : what about writing a Python Hub-like tool? I've been looking for that but it's yet to be created.
That script could server as a first version. It would go on it's won repo, outside OCA.

**Comment by gurneyalex** [comment]
@dreispt Have you looked at the Python libraries listed on https://developer.github.com/libraries/?

**Comment by dreispt** [comment]
@gurneyalex No I haven't, thanks for the tip.

**Comment by moylop260** [comment]
Hello,
I tried unsuccessfully to use libraries

Then I copied this section code from runbot:
https://github.com/odoo/odoo-extra/blob/master/runbot/runbot.py#L224-L243

And later I use this method:
```python
    pr_data = {
        "title": title,
        "head": branch_head,
        "base": branch_base,
        "body": comment,
    }
    return github(repo_base=project_base,
                  url='/repos/:owner/:repo/pulls', payload=pr_data)
```
I don't have problem if we use library, but I don't found how use it to create a pull request.

**Comment by guewen** [comment]
IMO, the `maintainers-tools` project has not for purpose to reimplement `hub` in Python.
Why not improve an existing Python project or use `hub`?

**Comment by lmignon** [comment]
I agree with @guewen, IMO this functionality  should be provided by an existing python lib. If it doesn't exist, it would be nice to improve an existing lib. One common mistake in OSS is to reinvent in place of contribute..

**Comment by yvaucher** [comment]
I'll close this PR as the main opinion is that's out of scope of maintainer tools repository

**Pull request closed without merging**
