### PR TITLE
fix-exception UserError not in v8

### PR DESCRIPTION
**Pull request by bealdav**
The path to go from v8 to v9 is soft with this rule: 
- only import change
- inside use of UserError of the same for both

### CODE REVIEW

**Comment by guewen** [comment]
:+1:

**Comment by pedrobaeza** [comment]
Good trick with future version in mind :+1:

**Comment by jgrandguillaume** [comment]
:+1:

**Comment by bealdav** [comment]
@pedrobaeza it's an idea of @sebastienbeau. Surely a good idea

**Comment by pedrobaeza** [comment]
You all guys have very good ideas, and you also share with community, so it's awesome!

**Pull request merged**
