### PR TITLE
[ADD] gitignore: mac .DS_Store

### PR DESCRIPTION
**Pull request by mreficent**
I have seen some people using it.

### CODE REVIEW

**Comment by mreficent** [comment]
@lasley, maybe. I think both files should have the same exclusions, or at least we should try that them have the maximum of exclusions in common possible.

**Comment by lasley** [comment]
I agree @mreficent - consistency is key IMO. Can you please bring over the template here then?

**Comment by mreficent** [comment]
@lasley comparing the two templates, what I see is that the **maintainer-tools** template (with this PR) includes all exclusions listed in the **maintainer-quality-tools** template. However, that template in **maintainer-quality-tools** is the incomplete one!

**Comment by lasley** [comment]
Ah seems you're right @mreficent. I'll merge this one then.

Did you want to tackle updating the template in MQT for us as well?

**Pull request merged**
