### PR TITLE
[IMP] oca-gen-addon-readme: stop emitting an XML declaration

### PR DESCRIPTION
**Pull request by nilshamerlinck**
https://github.com/OCA/maintainer-tools/issues/595

### CODE REVIEW

**Comment by pedrobaeza** [comment]
But this should be only for 17.0, not the rest of the versions.

**Review by bosd — APPROVED** [review]
LGTM, dunno if it is a blocker to do this for all versions

**Comment by nilshamerlinck** [comment]
Hello guys :)
- thanks for looking into this PR!
- it's ok to apply this change for all versions: it will not change anything even for old odoo instances that would not have been patched with the fixes https://github.com/odoo/odoo/pull/133708 and https://github.com/odoo/odoo/pull/133900
- that's because we never actually strictly needed the XML declaration, because `docutils` also adds this meta tag in the `index.html`: `<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />` that is respected by the `HTMLParser` used by `lxml.html.document_fromstring(doc)`
- I updated the commit to make this a bit more explicit

**Comment by sbidoul** [comment]
Thanks!

**Pull request merged**
