### PR TITLE
[ADD] oca-bdist-all-wheels

### PR DESCRIPTION
**Pull request by sbidoul**
**WIP - do not merge** 

I'm creating this PR to show what I'm aiming at.

This trivial scripts creates wheel [1] packages for all odoo addons it discovers in subdirectories. In a nutshell, it does `python setup.py bdist_wheel` recursively and nothing else.

It is built on the foundation laid out in [2][3].

Typical use (pseudo code):
```
virtualenv .
. bin/activate
pip install maintainer-tools
pip install setuptools-odoo
pip install wheel
oca-clone-everything
oca-bdist-all-wheels --dist-dir ~/wheelhouse
```

Then you can install addons with (pseudo code):
```
virtualenv .
. bin/activate
# install odoo requirements and odoo in the virtualenv
# ...
pip install setuptools-odoo
# install an addon, automatically fetching all dependencies
pip install odoo-addon-<addon-name> --find-links=~/wheelhouse
# start odoo without addon path
odoo-server-autodiscover
```

What's next?
- [ ] finish setuptools-odoo [3]
  * [x] addons in install_requires https://github.com/acsone/setuptools-odoo/commit/5dbe445bc2be52a06f84f2f7617db84c978c2f15
  * [x] external_dependencies['python'] in install_requires https://github.com/acsone/setuptools-odoo/commit/b76e98c299da5642cb927a920ba85baa076509ab
  * [x] package static folder and all other non-python files (views, csv, etc) https://github.com/acsone/setuptools-odoo/commit/3826a286729ea61460342bb49290a7cebc3ef717
  * [ ] author, author_email
  * [x] url
  * [x] tests
  * [x] refactoring for modularity (setuptools-odoo version 0.7.1)
  * [x] basic documentation
  * [ ] finish api documentation
  * [x] provide a simple mechanism to override autodected dependencies (and specify minimum odoo addon version for instance)
- [x] see what development and deployment of a real project purely based on virtualenv+pip would look like (https://github.com/pypa/pip/issues/3 is annoying... or maybe not, thanks to Odoo's custom import hook) - update it works quite nicely

And then we can think about creating https://wheelhouse.odoo-community.org.

[1] https://pypi.python.org/pypi/wheel
[2] https://github.com/OCA/maintainer-tools/issues/116#issuecomment-145250154
[3] https://github.com/acsone/setuptools-odoo

### CODE REVIEW

**Comment by sbidoul** [comment]
Update: here is what works today.

```sh
#!/bin/sh
virtualenv env
. env/bin/activate

# install setuptools-odoo to get odoo-server-autodiscover
pip install git+https://github.com/acsone/setuptools-odoo.git

# prepare wheels for odoo requirements (do this only once, so later builds are faster)
pip wheel -w ../OCA/gat/wheelhouse-odooreq -r https://raw.githubusercontent.com/odoo/odoo/8.0/requirements.txt

# note: wheelhouse-oca is built with https://github.com/OCA/maintainer-tools/pull/156

# install Odoo
pip install ~/Downloads/odoo_8.0.latest.zip --find-links=../OCA/gat/wheelhouse-odooreq --no-index

# install two addons from wheel package, additional dependencies installed automatically
pip install odoo-addon-base_import_async odoo-addon-web_sheet_full_width --find-links=../OCA/gat/wheelhouse-oca --no-index
# install from local copy
pip install ../OCA/gat/server-tools/disable_openerp_online --find-links=../OCA/gat/wheelhouse-oca --no-index
# install in editable (develop) mode from local copy
pip install -e ../OCA/gat/l10n-belgium/l10n_be_mis_reports --find-links=../OCA/gat/wheelhouse-oca --no-index

# look 'ma, no --addon-path
odoo-server-autodiscover
```

**Comment by max3903** [comment]
```$ pip install odoo-addon-base_import_async odoo-addon-web_sheet_full_width --find-links=../OCA/gat/wheelhouse-oca --no-index
Ignoring indexes: https://pypi.python.org/simple/
Downloading/unpacking odoo-addon-base-import-async
  Could not find any downloads that satisfy the requirement odoo-addon-base-import-async
Cleaning up...
```

**Comment by sbidoul** [comment]
@max3903 the procedure was pseudocode indeed. I created a test wheelhouse and updated https://github.com/OCA/maintainer-tools/pull/156#issuecomment-157046354 above. It should work as written now.

**Comment by gurneyalex** [comment]
@lepistone @guewen is this something which you could use in your current dev?

**Comment by lepistone** [comment]
I haven't yet tested the work of @sbidoul @max3903 @dreispt and all others involved, but that looks awesome, thanks! I would very much love to generate python packages for individual modules, instead of the current buildout + git clone approach.

I feel python packages are the way to go indeed.

To answer @gurneyalex, at some point yes! This is probably orthogonal to the Continuous Delivery Docker work: in any case it will be great to use python packages instead of git clones (be them git submodules of managed by anybox buildout).

**Comment by sbidoul** [comment]
@lepistone @gurneyalex FYI, regarding the development workflow, I'm aiming at releasing a customer project with `pip freeze | pip wheel -r /dev/stdin --wheel-dir=release`. I'm 3 pip bugs from that goal...

But that's orthogonal to the packaging and distribution discussed in this PR.

**Comment by max3903** [comment]
:+1:

**Comment by sbidoul** [comment]
I implemented an automatic post-versioning mechanism. Addons which have had commit after the last version change: https://github.com/acsone/setuptools-odoo#versioning.

So commits that do not change the addon version are considered developmental. They will be packaged but will not be installed automatically unless people use `pip install --pre` to explicitly require them.

**Comment by sbidoul** [comment]
This one is now ready for merging, it's running in production on odoo-community.org to produce https://wheelhouse.odoo-community.org/

**Pull request merged**
