### PR TITLE
[IMP] runbot_with_ids.txt: Fix typo for realestate

### PR DESCRIPTION
**Pull request by rousseldenis**
@simahawk Missed this one for gen-addon-readme

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Shouldn't we update the README template for using new runboat links?

**Comment by simahawk** [comment]
The fix is legit but... do we still need this file at all? There's no "runbot" anymore for OCA.

**Comment by rousseldenis** [comment]
> The fix is legit but... do we still need this file at all? There's no "runbot" anymore for OCA.

Yes. But this is to restablish a sane situation.

gen-addon-readme does not work anymore for that repository as it relies on this file.

I don't know the real implementation of the tool, maybe something ha to be done there too

**Comment by rousseldenis** [comment]
There is already this : https://github.com/OCA/maintainer-tools/issues/524

**Comment by rousseldenis** [comment]
> Shouldn't we update the README template for using new runboat links?

@pedrobaeza Should be done there : https://github.com/OCA/maintainer-tools/blob/master/tools/gen_addon_readme.py#L202

As template is interpreting 'badges' variable.

**Comment by rousseldenis** [comment]
Done there : #534

**Comment by simahawk** [comment]
Cool, thanks!

**Pull request merged**
