### PR TITLE
[IMP] Include tests folders in CONTRIBUTING.md

### LINKED ISSUE #103: [REF] contributing: missing test and tests folder
I don't saw test folder in guidelines of contributing.

TODO: Make PR with this guideline

### PR DESCRIPTION
**Pull request by pedrobaeza**
Closes #103

### CODE REVIEW

**Comment by hbrunn** [comment]
:+1:

**Comment by elicoidal** [comment]
:+1:

**Comment by bealdav** [comment]
sorry to give this info now but why promote yaml test in guidelines ?
yml

**Comment by pedrobaeza** [comment]
@bealdav, it's not being promoted, simply exposed that for now (and until removed), you should place this kind of tests in that folder. We should cover all the possible folders/files in the structure. We can warn in another section about the deprecated condition, but not to simply remove the reference.

**Comment by dreispt** [comment]
I disagree with having both a `/test` and a `/tests` directories.
We should stick to only one, and that should be `/tests`.

PS: can we leave some room for discussion before merging PRs?

**Comment by bealdav** [comment]
:+1: Daniel

**Comment by pedrobaeza** [comment]
@dreispt, you can't disagree because this is something standard that Odoo "imposes", not ours. And it has been quickly merged because everyone has this clear. Anyways, we can make all the PRs amending things that we want. GitHub doesn't charge us the number of PRs :smile:

**Comment by dreispt** [comment]
@pedrobaeza I just checked the [Odoo guidelines](https://github.com/odoo/odoo/blob/9.0/doc/reference/guidelines.rst#directories) and they support my view: tests should go in the `/tests` directory.

**Comment by elicoidal** [comment]
@all: sorry for the quick merging.
It was not intended to avoid the discussion: I just thought it was consensual (and I was wrong :()

**Comment by dreispt** [comment]
@elicoidal No problem.
To be clear, I've been the one advocating "optimistic merges", but that does not necessarily mean to merge as quickly as possible 😄

**Comment by elicoidal** [comment]
:D

**Comment by pedrobaeza** [comment]
@dreispt, they have changed their guidelines then from 8.0, where both folders are found. Please make then a PR amending this.

**Comment by pedrobaeza** [comment]
It's already in https://github.com/OCA/maintainer-tools/pull/202

**Pull request merged**
