### PR TITLE
Add 'Translate me' badge in readme

### PR DESCRIPTION
**Pull request by sbidoul**
image

Similar to the `runbot | Try me` badge.

### CODE REVIEW

**Comment by sbidoul** [comment]
> Should we added to README example too?

No. This will be added automatically.

**Comment by pedrobaeza** [comment]
Well, I wanted to keep it a bit more for having in the same commit this update and the one in the new issue link, but too late..

**Comment by sbidoul** [comment]
@pedrobaeza for now it requires a manual deployment on the OCA server to become active, so no harm done.

**Comment by pedrobaeza** [comment]
Ah, right! Then the manual README generation I made tonight on 2 modules on PRs will be rolled-back, hehe. I'll tell you about the issue link

**Pull request merged**
