### PR TITLE
ADD .. figure::  example

### PR DESCRIPTION
**Pull request by eLBati**

### CODE REVIEW

**Comment by dreispt** [comment]
:+1:

**Comment by osvalr** [comment]
:+1:

**Comment by moylop260** [comment]
:+1: thanks

**Comment by elicoidal** [comment]
As we are talking about the subject, may I suggest to add:
   :width: 600 px
   :alt: alternative description

**Comment by elicoidal** [comment]
:+1:

**Comment by pedrobaeza** [comment]
:+1: with Eric's proposition to limit the size to avoid ugly layouts

**Comment by eLBati** [comment]
@elicoidal thanks, done

**Pull request merged**
