### PR TITLE
[ADD] README.rst generator from __openerp__.py

### PR DESCRIPTION
**Pull request by charbeljc**
* add a requirement on https://github.com/charbeljc/pystache.git, waiting for the following pending PRs:
   * https://github.com/defunkt/pystache/pull/176
   * https://github.com/defunkt/pystache/pull/177
   * https://github.com/defunkt/pystache/pull/178

### CODE REVIEW

**Comment by dreispt** [comment]
Why add another templating lib when we already have so many options available? 
I believe that the same effect could be easilly achieved with `.format()`...

**Comment by charbeljc** [comment]
Hi @dreispt, thank you for your comments. Maybe I would have achieved the same effect using `.format()`, but with less elegance. With my additions to `pystache`, you can for instance write things like this.

```python
...
def under(a):
   return '\n'.join([a, '=' * len(a)])
renderer.register_helper('=', under) 
print renderer.render('...\n{{= name}}\n...', {'name': 'Section 1'})
``` 
This will expand to:
```
...
Section 1
=========
...
````
Besides, `pystache` as many other useful features making it a valuable addition in our toolchain.

Regards

**Comment by dreispt** [comment]
Personally, I try to avoid additional dependencies as much as I can. But that's my personal opinion.

**Comment by guewen** [comment]
I tend to agree with @dreispt and if we have to choose to add a dependency, I would consider other choices, such as for instance cookiecutter which can also injects user inputs and default values (in user's configuration files) (which we'll need for filling the templates).

**Comment by moylop260** [comment]
@charbeljc 
Good job, good feature!
:+1:

**Comment by moylop260** [comment]
@guewen and @dreispt 
I'm agree with you.
It can use webkit template too.
However, we need to add new library to requirements.txt too.
Maybe `pystache` is a good library too (I don't know)
We will need to talk about what is the better library to use templates in OCA. (other issue).
But now, If we don't have this rule IMHO we can't to block PR, what do you think?

**Comment by dreispt** [comment]
We already have Jinja and Mako as Odoo dependencies. I honestly don't see the need for yet  another templating lib.

**Comment by moylop260** [comment]
We can define then that our templates script should be based on Mako or Jinja.
Right?

**Comment by nhomar** [comment]
I this time prefer do this based on cookiecutter which use jinja BTW and is really good tested.

We know Mako, Jinja now we Learn Qweb, Honestly I do not have any preference, but I do not want to use another one.

Regards.

**Comment by charbeljc** [comment]
Hum, @guewen, @nhomar `cookiecutters` looks nice, I will test it later, as soon as my projects deadlines are done, thanks for the pointer

**Comment by max3903** [comment]
I agree with @guewen and @dreispt 

:-1:

**Comment by gurneyalex** [comment]
:-1:

closing.

**Pull request closed without merging**
