### PR TITLE
Add guidelines for placing reports

### LINKED ISSUE #87: No guidelines given for placing reports in modules
The guidelines state where we should store the models, views etc, but does not indicate where reports must go.

### PR DESCRIPTION
**Pull request by clonedagain**
Seems to be the current convention used at Odoo SA's.
Fixes #87

### CODE REVIEW

**Comment by dreispt** [comment]
:+1:

**Comment by dreispt** [comment]
Should that list have a criteria to order it's entries?

**Comment by clonedagain** [comment]
Updated PR to indicate where to place the report files in the complete tree. Is it correct?

**Comment by guewen** [comment]
Follows the changes in Odoo, :+1: 
Thanks!

**Comment by bwrsandman** [comment]
:+1:

**Pull request merged**
