### PR TITLE
[IMP] Version-specific website tour code samples

### PR DESCRIPTION
**Pull request by Yajo**
This specific part of odoo changes a bit depending on your Odoo version.

Reflecting it in the template will help when developing a new addon.

cc @chienandalu

### CODE REVIEW

**Review by chienandalu — APPROVED** [review]
:+1:

**Comment by pedrobaeza** [comment]
CI is failing. I wouldn't change the method name, but put the proper one, and prefix a comment explaining which one for each version.

**Comment by Yajo** [comment]
So, your suggestion is that I create 3 methods with the same name?

**Comment by pedrobaeza** [comment]
Yes. If not, people may think that the method name is that one.

**Comment by Yajo** [comment]
Fixed.

**Comment by pedrobaeza** [comment]
I still think creating 3 methods with the same name is the correct thing, as:

- It's easier to delete non proper ones.
- Linters will complain if you leave several of them.
- Comment about the usage can be put as docstring and more easily identifiable.

**Comment by Yajo** [comment]
Done

**Review by pedrobaeza — APPROVED** [review]
I don't know though why CI is red.

**Comment by Yajo** [comment]
It seems some misconfiguration with coveralls. But this has nothing to do with CI, right? This is just dead code to copy and paste elsewhere, I don't think those ❌ are important here.

**Comment by pedrobaeza** [comment]
Well, we should fix it. I think @sbidoul fix a similar thing recently. Do you have a clue?

**Comment by Yajo** [comment]
Yes, although that is obviously a totally different issue. I think we can merge this.

**Comment by pedrobaeza** [comment]
Well, although unrelated indeed, merging something red is not usual, so I let @sbidoul to decide about that.

**Comment by sbidoul** [comment]
I fixed the coveralls issue in #497

**Pull request merged**
