### PR TITLE
fix setup.cfg and add some documentation

### PR DESCRIPTION
**Pull request by gurneyalex**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by moylop260** [comment]
:+1:

**Comment by pedrobaeza** [comment]
It seems to be a flake8 error:
```
tools/clone_everything.py:16:80: E501 line too long (89 > 79 characters)
```
Can you fix it at the same time?

**Comment by gurneyalex** [comment]
@pedrobaeza good catch, this was hidden by the lack of a `.py` extension in the previous version.

**Comment by pedrobaeza** [comment]
I merge it then.

**Comment by gurneyalex** [comment]
thanks. I hope you people will find the updated script as useful as I do.

**Comment by pedrobaeza** [comment]
I think so. I'm just right now preparing for having all modules cloned. I just had some of them cloned by demand.

**Pull request merged**
