### PR TITLE
[ADD] add series labels

### PR DESCRIPTION
**Pull request by sbidoul**
I would like to reintroduce series labels in repositories as it was in the past (7, 8).

I don't remember when and why the switch was made to use milestones to identify the Odoo series. It has the downside of preventing traditional uses of milestones, ie for release planning and managing the roadmap. In OCA/mis-builder for instance this proves tremendously [useful](https://github.com/OCA/mis-builder/milestones). 

So I would like to progressively re-encourage the use of labels, while leaving freedom to repo maintainers to make the best use of milestone.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
We are using milestones for setting the version target. It's easier to manage and can be done by the author of the PR.

**Comment by sbidoul** [comment]
@pedrobaeza AFAIU setting labels and milestones are subject to the [same permissions](https://help.github.com/articles/repository-permission-levels-for-an-organization/).

**Comment by pedrobaeza** [comment]
Uhm, maybe it's because the new "OCA contributors" team we set that they are now able to do it. Any way, I still prefer to use milestones, as they don't have any other use and they are already created on the branch migration.

**Comment by sbidoul** [comment]
@pedrobaeza my point is that milestones do have other uses. See [here](https://github.com/OCA/mis-builder/milestones) for example.

**Comment by pedrobaeza** [comment]
You are the only one using that approach. The rest of OCA don't and uses the milestone=version one.

**Comment by lasley** [comment]
I agree with Pedro on the overall use of milestones for target versions.

I see the other uses, however. I think this would be better left as an exclusion a PSC can make contextually. Once we get vertical-medical API stable, we'd probably do the same thing.

**Comment by lmignon** [comment]
I'm also in favor of being able to use milestone for what they're supposed to do. With the goal to get a better release management of an addon, this functionality makes sense. Using milestones to identify the series makes it impossible to use the tools available in github to effectively manage the lifecycle of an addon. I think it is therefore important that a PSC has the opportunity to opt for this approach.

**Comment by leemannd** [comment]
@pedrobaeza @sbidoul I'm member of the OCA/contributor's group, but I'm not able to put a label nor a milestone on my own PR

**Comment by lasley** [comment]
@leemannd - please create an issue for that and tag us so we can stay on topic in this one.

**Comment by pedrobaeza** [comment]
@leemannd I remember to see that, but maybe he/she was PSC and I didn't notice...

About the milestone thing, of course each PSC can decide, but this PR is for putting version labels on all repositories, and thus, :-1: for that.

**Comment by lasley** [comment]
Forgive the ignorance, but how is this script run? If it's something run locally, perhaps and environment variable?

**Comment by lasley** [comment]
Actually CLI flag would be better than ENV. I forget not everything is Docker 😆

**Comment by sbidoul** [comment]
> I'm member of the OCA/contributor's group, but I'm not able to put a label nor a milestone on my own PR

You need write access to the repo to do that which Contributors don't have. It's normal, there is nothing we can do about that.

**Comment by pedrobaeza** [comment]
It's run by hand, but for all the projects. It can be acceptable if the series labels is opt-in.

**Comment by pedrobaeza** [comment]
> You need write access to the repo to do that which Contributors don't have. It's normal, there is nothing we can do about that.

Uhm, I thought the contributors team mitigates that, but it doesn't help either.

**Comment by lasley** [comment]
> Uhm, I thought the contributors team mitigates that, but it doesn't help either.

This is one of the main things I hate about Github permissions. The team permissions must be set at the repo level - all a team does by default (unless it's an admin team) is allow grouping 😦

**Comment by leemannd** [comment]
I'm not trying to devert the original topic nor gaining more acces I just must have misunderstood these two lines. That said, I'm out ;)

> We are using milestones for setting the version target. It's easier to manage and can be done by the author of the PR.
> Uhm, maybe it's because the new "OCA contributors" team we set that they are now able to do it.

**Comment by pedrobaeza** [comment]
@leemannd, don't worry. It has been my misunderstanding of GitHub uses. As said, that's another issue, as you don't have access neither labels nor milestones, so that's not a decision factor for this PR.

**Comment by lasley** [comment]
@leemannd I think you should still create the issue as I recommended. You are not out of line here, I'm pretty sure what you think was our intent.

**Comment by pedrobaeza** [comment]
Closing as there's no agreement. Whoever wants series in the labels, he/she should create them manually.

**Pull request closed without merging**
