### PR TITLE
pypi upload script, with caching

### PR DESCRIPTION
**Pull request by sbidoul**
A thin wrapper around twine, with a local cache of what has already been uploaded.

### CODE REVIEW

**Comment by sbidoul** [comment]
A sample is being uploaded to https://testpypi.python.org/pypi

**Comment by sbidoul** [comment]
@lmignon @dreispt @max3903 anyone else, can you have a look at the odoo packages sample published on testpypi.python.org and see if you spot anything suspicious.

If not, I'll soon launch the upload to pypi.python.org.

**Comment by max3903** [comment]
LGTM :+1:

**Comment by sbidoul** [comment]
I patched the existing wheels to insert the trove classifiers, and I uploaded a sample to [pypi production](https://pypi.python.org/pypi?:action=browse&c=624) (pending indexation by pypi).

`pip install odoo10_addon_mis_builder` should just work.

@lmignon @max3903, anyone else, can you do a sanity check? 

Then I'll launch the upload of those 2500 packages, 12000 wheels, 1.5GB (!) to pypi (I've a weird feeling about this...).

**Comment by max3903** [comment]
@sbidoul What do you mean by weird feeling? We have contacts at the PSF in the OCA instance if you want to let them know first...

**Comment by sbidoul** [comment]
@max3903 well... uploading to pypi is irreversible: once a version has been uploaded it cannot be changed unless uploading a new version, so it must be perfect first time.

**Comment by max3903** [comment]
@sbidoul If you go to files or releases, you can remove them.

**Comment by pedrobaeza** [comment]
Maybe a reduced test over one module/repository?

**Comment by sbidoul** [comment]
@max3903 yes but you cannot re-add a file with the same name. It's a good feature of pypi, that once you have frozen a dependency, you are guaranteed to get the exact same file in the future (unless the file has been removed).

@pedrobaeza what do you mean?

**Comment by pedrobaeza** [comment]
I mean to try only to upload one repository, not whole OCA.

**Comment by sbidoul** [comment]
> I mean to try only to upload one repository, not whole OCA.

@pedrobaeza  ah, that I have done: https://pypi.python.org/pypi?:action=browse&c=624

You can `pip install odoo10-addon-mis_builder`, it just works.

**Comment by pedrobaeza** [comment]
OK, then have a little faith my friend!! :smile:

**Comment by max3903** [comment]
@sbidoul I agree with @pedrobaeza. There is only one way to know. Let's go for it!

**Comment by lmignon** [comment]
@sbidoul Everything seems OK ... :+1:

**Comment by sbidoul** [comment]
All 10.0 packages are on pypi. It's now uploading 8.0.

**Comment by pedrobaeza** [comment]
:clap: :clap:

**Comment by lmignon** [comment]
@sbidoul A nice to have should be to have the repository url referenced somewhere into the package description. For the moment, It's not possible to know where to find the dev repository.

**Comment by sbidoul** [comment]
@lmignon yes, that and many more. These things go in the description field of the package, which is the addon README.rst.

Now that I'm getting packaging out of the way, I'm considering to dedicate some of my OCA brainshare to working on these documentation aspects (ie autogenerating the OCA boilerplate in the README files, managing the images properly, etc) so we have nice and consistent documentation across the distribution platforms.

**Comment by max3903** [comment]
@sbidoul Congratulations! Great achievement. Thanks.

**Pull request merged**
