### PR TITLE
[FIX] Work around Transifex/Rackspace limitations

### PR DESCRIPTION
**Pull request by max3903**

### CODE REVIEW

**Comment by max3903** [comment]
Seems to be working:
https://github.com/oca-transbot

**Comment by moylop260** [comment]
@max3903 
Can you explain a little more this patch?

**Comment by max3903** [comment]
@moylop260 Sure. We hit some Rackspace limitations:
http://docs.rackspace.com/loadbalancers/api/v1.0/clb-devguide/content/Rate_Limits-d1e821.html

so I paused the script at the end of a file and at the end of a project.

**Comment by moylop260** [comment]
Can you use cron?
https://github.com/OCA/maintainer-tools/blob/master/Dockerfile-tx-bot#L38-L40

**Comment by max3903** [comment]
@moylop260 I already do. The script is run once a week. The problem is that it connects too often to Transifex during the execution.

**Comment by pedrobaeza** [comment]
Please add a little comment over each sleep to tell about the problem, but :+1:

**Comment by pedrobaeza** [comment]
For references, see this section in Transifex API doc: http://docs.transifex.com/api/#api-rate-limits. The one that is struggling us is the throttling in Django.

**Comment by lmignon** [comment]
:+1:

**Comment by sbidoul** [comment]
:+1: merging since it's running fine in production.

**Pull request merged**
