### PR TITLE
[FIX] gen_addon_readme.template: Avoid trailing whitespace

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
### Fixes
- Avoid the fucking trailing whitespace:

Selection_111

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
@sbidoul please, could you give me some tips of what should I change to make this green?

**Comment by sbidoul** [comment]
@MiquelRForgeFlow I guess the whitespace between badges is important.

In any case I would wait for another more significant change in the readme generator. Removing a trailing whitespace is not worth regenerating thousands of README files and pushing thousands of packages to PyPI.

Does this trailing space cause issues in practice?

**Comment by MiquelRForgeFlow** [comment]
No, it doesn't cause issues. Just that each time I do a module migration, I see that trailing whitespace in the readmes be deleted and later put again and I thought we could put aside that silliness.

**Comment by sbidoul** [comment]
> I see that trailing whitespace in the readmes be deleted

Do you know what deletes it?

**Comment by pedrobaeza** [comment]
@sbidoul IDEs perform the deletion with the option "remove trailing spaces" activated that lots of people have activated (me included).

**Comment by MiquelRForgeFlow** [comment]
@sbidoul now this PR is green and ready to merge 🚀

**Comment by sbidoul** [comment]
> IDEs perform the deletion with the option "remove trailing spaces" activated that lots of people have activated (me included).

Yes, but don't these IDE do that on save, which you normally don't do on README.rst?

**Comment by pedrobaeza** [comment]
> Yes, but don't these IDE do that on save, which you normally don't do on README.rst?

Yeah, indeed, but sometimes you change a letter in the fragment and don't want to re-run the tool, or you save by accident/habit with no change.

**Comment by MiquelRForgeFlow** [comment]
> you change a letter in the fragment and don't want to re-run the tool

Exactly, I normally run _replace in path_ ("12.0"->"13.0" and "12-0"->"13-0") to avoid re-running the tool.

**Comment by sbidoul** [comment]
I think we'll put gen-addon-readme in the pre-commit config for 13, as Jairo suggested.

**Comment by MiquelRForgeFlow** [comment]
But I don't run pre-commit and don't want to be forced to run that. I prefer running black, isort and such manually.

**Comment by pedrobaeza** [comment]
@MiquelRForgeFlow that's a bit obstinacy: having it integrated in pre-commit is OK and it's more comfortable than doing it manually.

Yes, let's go for that, @sbidoul

**Comment by MiquelRForgeFlow** [comment]
Well, maybe I didn't express correctly. My point is, instead of forcing the user to do more things (like running pre-commit or gen-addon-readme) before pushing, let's automatize more things, creating bots that after merging or pushing create black/isort commits. Instead of a pre-commit thing, let's call a post-merge thing. Let's welcome bots technology instead of manually do things. I don't like running tools, I prefer bots running tools.

**Comment by pedrobaeza** [comment]
pre-commit is for that: for not having to do anything except the initial setup: then everything is done by a bot while you commit, but the "bot" is in your local.

**Comment by MiquelRForgeFlow** [comment]
The bots should be "online", not "local".

**Comment by pedrobaeza** [comment]
I prefer the contrary for reducing the noise of extra commits.

**Comment by MiquelRForgeFlow** [comment]
Extra commits are inevitable. Readme commit, icon commit, translation commit, .pot commit, etc. One more commit for black/isort things doesn't add really much noise.

**Comment by pedrobaeza** [comment]
Generating the README, the icon, etc in your local pre-commit avoids that extra commits. I'm not talking about the "isort, black" one that is performed before the migration for accommodating in the migration the old code. If you see, when you write new code for your migration, black automatically formats it and you include it on your migration commit, not on a new one.

**Comment by sbidoul** [comment]
@MiquelRForgeFlow black/isort is different, because it touches the code. If you have a bot doing extra code formatting commits, git blame becomes a nightmare. So that's clear to me, black stays in pre-commit *and* as a lint check. The rest (readme generator, .pot generator) is optional locally and will continue to be done by the bots.

**Comment by MiquelRForgeFlow** [comment]
Well, ok, I was just expressing my point of view. But let's leave it here, all this talk is outside of the topic of this PR.

**Comment by dreispt** [comment]
Can the READMEs be regenerated only for the modules involved in the PR?
We are already doing that for linting, right?

**Comment by sbidoul** [comment]
Since ocabot merge seems to be widely used, we could regenerate addons READMEs only when doing ocabot merge, and remove it from the nightly jobs. Although there are still people merging manually here and there.

**Comment by MiquelRForgeFlow** [comment]
> we could regenerate addons READMEs only when doing ocabot merge, and remove it from the nightly jobs

It seems to me we could do this nowadays, right?

**Pull request merged**
