### PR TITLE
[REM] useless link https://www.odoo.com/forum/help-1

### PR DESCRIPTION
**Pull request by tafaRU**
Following https://github.com/OCA/server-tools/pull/261#discussion_r40427477

### CODE REVIEW

**Comment by pedrobaeza** [comment]
As we already have Bug tracker section, I see the other link useless (because OCA doesn't attend specifically Odoo general forum), so :+1: 

Also consider to set an OCA forum is not the more proper thing, as people will mix concepts regarding specific OCA topics with another newbie general questions.

**Comment by eLBati** [comment]
:+1:

**Comment by StefanRijnhart** [comment]
:+1:

**Comment by moylop260** [comment]
:+1:

**Comment by dreispt** [comment]
:100:

**Pull request merged**
