### PR TITLE
[IMP] Default template icon

### PR DESCRIPTION
**Pull request by pedrobaeza**
Following #52 discussion, I propose a default icon that is more neutral, but distinguishes from the rest of the modules and promotes OCA's brand.

### CODE REVIEW

**Comment by guewen** [comment]
Nice!

**Comment by sebastienbeau** [comment]
:+1: 
Good work !

**Comment by lmignon** [comment]
:+1:

**Comment by rvalyi** [comment]
:+1:

**Comment by max3903** [comment]
The logo on the top side would be even nicer.

:+1:

**Comment by pedrobaeza** [comment]
@max3903, I tried to put on all the three visible sides, but it looks weird on the top one. That's why I left it this way.

**Pull request merged**
