### PR TITLE
Include eggs folder on .gitignore, on MAc OS it is created with python setup.py install.

### PR DESCRIPTION
**Pull request by nhomar**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I don't use Mac, but I suppose it can be. I prefer anyhow to add another line for explicitely say eggs instead of adding a wildcard that can exclude another files like egg_model.py

**Comment by yvaucher** [comment]
@nhomar You know that you can setup a default gitignore file on you local config?

As @pedrobaeza it would be better to add an accurate name.

**Comment by nhomar** [comment]
I close this. whatever! seriously.... (if in ANY os you generate a file with the setup.py the rule is include it in order to avoid miss commits)..

**Comment by yvaucher** [comment]
@nhomar Your PR is valid it is just that it would be preferable to have:

    *.egg
    *.eggs

As *.egg* might be to wide.

**Comment by nhomar** [comment]
@yvaucher done the change.

**Comment by yvaucher** [comment]
@nhomar thanks
:+1:

**Comment by pedrobaeza** [comment]
:+1:

**Comment by dreispt** [comment]
:+1:

**Pull request merged**
