### PR TITLE
[IMP] Add pre-commit installation session

### PR DESCRIPTION
**Pull request by Tonow-c2c**
Translation from https://github.com/OCA/l10n-brazil/wiki/Pre-commit-hook

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Not sure this should be here, as pre-commit is not needed for running maintainer-toolds.

**Comment by Tonow-c2c** [comment]
@pedrobaeza I agree with you may be we should add new repos for _procedure/documentation_ or a section in https://odoo-community.org/page/documentation where people can propose changes
but a very clear place to share procedures, knowledge and best practices

**Comment by pedrobaeza** [comment]
For me that place is the wiki about migration to version 13.0, that is referenced in each migration issue and that is where the change for black is happening.

**Comment by Tonow-c2c** [comment]
So can you add some help on this wiki https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0 to explain how to install pre-commit and use or a link to https://pre-commit.com/ ?

**Comment by pedrobaeza** [comment]
Well, specific tools deployment shouldn't be there. We can add a link to other place, but installing pre-commit shouldn't be something to be put in a migration wiki. There's already the mentioning of pre-commit needing to be run in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0#howto. Reading these instructions, I see that I didn't need to do all this stuff for making it work and this is something unnecessary complicated IMO. @sbidoul's blog post was enough for me.

**Pull request closed without merging**
