### PR TITLE
Changes in order to push 10.0 branches to OCA projects

### PR DESCRIPTION
**Pull request by StefanRijnhart**
[RFR] Check \_\_manifest\_\_.py when generating addons tables
and migrating branches
[IMP] Rename manifest to \_\_manifest\_\_.py for 10.0 branches
[FIX] Fetch the tree of the target branch, not of the project main branch
[IMP] Fix missing comma when adding dictionary entry
[IMP] Sort modules by name on the migration issue
[ADD] Delete setup addon directories on branch migration

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
cc @pedrobaeza, @sbidoul

**Comment by StefanRijnhart** [comment]
See https://github.com/StefanRijnhart/server-tools/commits/10.0 for an example of the commits that this version of the script creates.

**Comment by dreispt** [comment]
Looks good :+1:
Do  we want to also delete the unported modules?

**Comment by pedrobaeza** [comment]
I miss the sorting of the module list in the issue, but I can add it later.

**Comment by sbidoul** [comment]
Looks good :+1:

**Comment by StefanRijnhart** [comment]
@pedrobaeza Hold on, let me do the sorting.

**Comment by StefanRijnhart** [comment]
@dreispt we always keep the unported modules so that the changes of the code migration can be reviewed relatively transparently, right?

**Comment by StefanRijnhart** [comment]
@pedrobaeza https://github.com/OCA/maintainer-tools/pull/227/commits/87d79bfa1b758de0e9603e2271b395668166c868

Leaving this to work in progress because I want to do one final test.

**Comment by StefanRijnhart** [comment]
So the good news is that we don't have to rename the manifest file, because the server does not attempt to load modules set to uninstallable. The bad news is that not all modules are set to uninstallable. To be continued.

**Comment by StefanRijnhart** [comment]
Current version is good to go. See the updated PR description above. Also updated is https://github.com/StefanRijnhart/server-tools/commits/10.0.

**Comment by StefanRijnhart** [comment]
Oh wait, maybe we want to rename the manifests to __manifest__.py?

**Comment by pedrobaeza** [comment]
We can let that task to be done in the migration process.

**Comment by sbidoul** [comment]
We need to remove the setup directories for imported add-ons but I can do it after running this script.

**Comment by StefanRijnhart** [comment]
I'll have a look, I am now in shape for working with the Github API ;-)

**Comment by StefanRijnhart** [comment]
Now removing setup addon dirs (@sbidoul, I hope this is alright) and renaming \_\_openerp\_\_.py to \_\_manifest\_\_.py.

**Comment by sbidoul** [comment]
@StefanRijnhart removing setup addon dirs is fine. Can't comment on the how as I'm not so much into the github api.

**Comment by pedrobaeza** [comment]
I'm afraid you can't remove a full folder directly. You have to remove file per file with the API.

**Pull request merged**
