### PR TITLE
[RFR] OpenUpgrade is an addons repo now

### PR DESCRIPTION
**Pull request by StefanRijnhart**
### Milestone (Odoo version)
- 16.0

### Module(s)
- 

### Fixes / new features
- Allow new series branches on the OpenUpgrade project to be created automatically

### CODE REVIEW

**Comment by pedrobaeza** [comment]
But as said on the issue, this can't be initialized the same way as the rest. It has its own specific CI.

**Comment by sbidoul** [comment]
Ok, then better leave it alone.

**Comment by StefanRijnhart** [comment]
Oh ok.

**Comment by legalsylvain** [comment]
> Now that I have prepared 15.0 branch, definitively this can't be templated, as there are very specific changes corresponding to OpenUpgrade, so it's worse to start for the template and change that things, that copying previous branch, and adapt it:

Thanks @pedrobaeza for this work !

**Pull request closed without merging**
