### PR TITLE
spell Copyright instead of symbol

### PR DESCRIPTION
**Pull request by lepistone**
In http://www.gnu.org/licenses/gpl-howto.html I read the sentence

    Always use the English word “Copyright”; by international convention,
    this is used worldwide, even for material in other languages. The
    copyright symbol “©” can be included if you wish (and your character set
    supports it), but it's not necessary. There is no legal significance to
    using the three-character sequence “(C)”, although it does no harm.

I think that means that the exact word "Copyright" is always necessary,
while the symbol is an optional addition.

### CODE REVIEW

**Comment by elicoidal** [comment]
:+1:

**Comment by dreispt** [comment]
:+1:

**Comment by sbidoul** [comment]
:+1:

**Comment by pedrobaeza** [comment]
Reading that, I understand that the symbol is an option (not complementary), and I prefer the symbol, because it gives more to put the rest of the text. For me, :-1:

**Comment by elicoidal** [comment]
@pedrobaeza Symbol is an abbreviation of Copyright and I am not sure about the rationale for keeping both.
It is like saying USA United States of America.
Here more does not mean better ("copyright" word is good enough to state that this is a copyright notice).
So still :+1: for @lepistone recommendation

**Comment by pedrobaeza** [comment]
@elicoidal, I don't want to use both. I want to use only the symbol.

**Comment by elicoidal** [comment]
> Always use the English word “Copyright”

If you want the symbol you need to add it on top of the word (AFAIU)

**Comment by pedrobaeza** [comment]
@elicoidal, if you read the rest, it mentions as optional the copyright. I interpret it as optional replacement, not as complementary.

**Comment by elicoidal** [comment]
@pedrobaeza This is crystal clear in the description:
Word "Copyright" is mandatory (**Always** use the English word “Copyright”)
Symbol is possible but optional (The copyright symbol “©” **can be** included if you wish)

I dont understand your standpoint here.

**Comment by pedrobaeza** [comment]
I don't see that clear, but anyways, proceed as you want.

**Comment by leemannd** [comment]
:+1:

**Comment by moylop260** [comment]
👍

**Comment by moylop260** [comment]
> @pedrobaeza  I don't see that clear, but anyways, proceed as you want.

I understand this as a lift of 👎
Then merging...

**Pull request merged**
