### PR TITLE
tools/copy_maintainers.py: handle two virtual teams

### PR DESCRIPTION
**Pull request by gurneyalex**
* OCA Contributors
* OCA Members

These teams are not linked to an OCA projet, but having them will gives some
visibility to the members and contributors of the association.

### Milestone (Odoo version)
- 

### Module(s)
- 

### Fixes / new features
-

### CODE REVIEW

**Comment by gurneyalex** [comment]
The code works fine. I'm baffled by the travis failure though...

**Comment by pedrobaeza** [comment]
@moylop260 can you help?

**Comment by moylop260** [comment]
I saw the same
 - `error in setup command: Error parsing /home/travis/build/OCA/maintainer-tools/setup.cfg: ImportError: No module named build_clib`

from [the last stable master travis build](https://travis-ci.org/OCA/maintainer-tools/builds/274505943#L662)

Because a red PR https://github.com/OCA/maintainer-tools/pull/288 was merged with that error.

**Comment by moylop260** [comment]
Really was a change of ubuntu distribution from travis jobs.
I have create the following fix https://github.com/OCA/maintainer-tools/pull/291

**Comment by moylop260** [comment]
@gurneyalex Could you help us to merge https://github.com/OCA/maintainer-tools/pull/291?

**Pull request merged**
