### PR TITLE
[IMP][RFC] oca-gen-addons-table : add developpement_status badge.

### PR DESCRIPTION
**Pull request by legalsylvain**
- Add maintainers column in the readme file of the repository.

The inserted image contains the following code 
``[MAINTAINER](https://github.com/MAINTAINER)``

- Add maturity badge in version column. 

**Result for the OCA/pos repository :**

image

Full result : https://github.com/legalsylvain/pos/tree/12.0-TEST-oca-gen-addons-table-maintainers

Thanks for your review.

CC : original author / commiter of this file : @sbidoul, @StefanRijnhart.
CC : @quentinDupont 

Closes: #454

### CODE REVIEW

**Comment by sbidoul** [comment]
CI is red, but otherwise :+1:

**Comment by rousseldenis** [comment]
Seems great indeed. +1 too

**Comment by legalsylvain** [comment]
Hi @sbidoul and @rousseldenis.

After thinking again regarding addons table, I'm not very confortable with the result of having a "Beta" value set by default. So : 
I split the two features : 
- the maintainers colum feature is done here : https://github.com/OCA/maintainer-tools/pull/506. I fixed tests, and i think it can be merged quickly
- Regarding status column I don't think that the current default "Beta" value is a good thing because we have no idea regarding the quality of the module. For the time being It is displaying 99% of the OCA module as "Beta" and it's not True. 

So, regarding that second point, i propose to display a bagde in the addons-table AND in the README file,ONLY if a value is explicitily set.
If you're ok, I'll update this PR, to patch also ``gen_addon_readme.py`` to remove badge if there is no value set in the ``developpement_status`` key.

**Comment by rousseldenis** [comment]
> Hi @sbidoul and @rousseldenis.
> 
> After thinking again regarding addons table, I'm not very confortable with the result of having a "Beta" value set by default. So :
> I split the two features :
> 
> * the maintainers colum feature is done here : [[IMP] add maintainers column in addons table. #454 #506](https://github.com/OCA/maintainer-tools/pull/506). I fixed tests, and i think it can be merged quickly
> * Regarding status column I don't think that the current default "Beta" value is a good thing because we have no idea regarding the quality of the module. For the time being It is displaying 99% of the OCA module as "Beta" and it's not True.
> 
> So, regarding that second point, i propose to display a bagde in the addons-table AND in the README file,ONLY if a value is explicitily set.
> If you're ok, I'll update this PR, to patch also `gen_addon_readme.py` to remove badge if there is no value set in the `developpement_status` key.

Yes, that will help finding modules that don't have development_status. +1

**Comment by sbidoul** [comment]
> After thinking again regarding addons table, I'm not very confortable with the result of having a "Beta" value set by default.

That is the reality of the default value, though. It might be useful to make it more visible so people think about it.

**Comment by legalsylvain** [comment]
Hi @sbidoul : 
> That is the reality of the default value, though

I understand your point. my though is just that there is a difference between "Beta" and "undefined". For the time being, 99% of the OCA has no development status defined. and there are not all in the "beta" status.
So, I think that letting blank if it's undefined and display real development status could be a great improvement. 

Alternatively, we can use a "Unknown" Status like this : 

image

**Comment by sbidoul** [comment]
The point is that it is not unknown. All our tooling considers it is Beta. Beta is displayed in the README, the [GitHub actions will test status compatibility](https://github.com/OCA/oca-addons-repo-template/pull/61/files#diff-1a1a06e77eea019f9a493c0ad1120d920d4c389fca8d74e7df059780d2b963afR82), etc.

So making this more visible should encourage people to explicitly define the status they want.

**Comment by sbidoul** [comment]
So you could show the Beta badge *plus* something else that says it came by default.

**Comment by legalsylvain** [comment]
> The point is that it is not unknown. All our tooling considers a missing status is Beta. Beta is displayed in the README, the GitHub actions will test status compatibility using Beta as default, they are published as Beta on PyPI, etc.

> So making this more visible should encourage people to explicitly define the status they really want.

My proposal is not to change github actions, pypi, etc... But just to avoid to display in the readme of the module, and the general readme of the repo, something wrong. (or automatically filled).

> So you could show the Beta badge plus something else that says it came by default.

Indeed. could be the solution. Even if i don't it know if it will be understandable.

Nevermind ! let's put this topic to rest and let other people express themselves on this subject.

could you review consensual #506 in the meantime ?

**Comment by sbidoul** [comment]
@legalsylvain what do we do with this ?

**Pull request closed without merging**
