### PR TITLE
Add suport for markdown fragments in the README.rst generator

### PR DESCRIPTION
**Pull request by sbidoul**
This PR adds support for authoring readme fragments in markdown.

It also add an option to convert existing reStructuredText fragments to markdown.

The generated `README.rst` remains reStructuredText, as before.

The main goal is to allow for easier documentation contributions by non-technical contributors (markdown is a simpler format, and has better tooling support - in particular it allows easy image drag and drop in GitHub's markdown editor).

### CODE REVIEW

**Comment by sbidoul** [comment]
@TumbaoJu

**Comment by sbidoul** [comment]
If there are no objections, I plan to merge this soon-ish and do some deeper tests. 

This is totally backward compatible.

**Review by pedrobaeza — APPROVED** [review]

**Comment by yajo** [comment]
Why is this lang translation needed? Wouldn't it be easier to render a README.md if fragments are on md, and a README.rst if they are on rst? 🤔 

After all, Odoo will only render the index.html anyways 🤷🏼‍♂️

**Review by yajo — APPROVED** [review]
My previous comment is non-blocking anyways 😉

**Comment by pedrobaeza** [comment]
Please let the RST generation. What I would remove is the HTML generation that is ugly and bloated.

**Comment by yajo** [comment]
If you want the README to be properly rendered on Github, the best is to have it on md. If you want it properly rendered on Odoo, the best is html. It seems to me like README.rst isn't really the best option for any of the main use cases we want to cover...

**Comment by sbidoul** [comment]
Note that if you have `README.md` but no `index.html`, Odoo parses `README.md` as reStructuredText.

So for now my plan is to keep generating `README.rst`.

**Comment by yajo** [comment]
> Note that if you have `README.md` but no `index.html`, Odoo parses `README.md` as reStructuredText.

Ah OK, then it makes sense. I thought that, if there's an `index.html`, Odoo forgot about any readmes.

**Comment by sbidoul** [comment]
An example conversion of the fragments from rst to markdown, on a repo with extensive documentation, is visible in https://github.com/OCA/rest-framework/pull/370

**Comment by yajo** [comment]
IMHO the template should include the fragments in markdown then.

**Pull request merged**
