### PR TITLE
[REF] add link to AGPL licence;

### PR DESCRIPTION
**Pull request by legalsylvain**

### CODE REVIEW

**Comment by max3903** [comment]
:+1:

**Comment by yvaucher** [comment]
:+1:

**Comment by pedrobaeza** [comment]
:+1:

**Comment by pedrobaeza** [comment]
@lmignon has mentioned on a PR that this badge is not shown in module form view and he proposes to move below the title

**Comment by lmignon** [comment]
@pedrobaeza You're right :smirk: Take a look to the app store and you'll see that the licence badge is missing on all OCA modules (except for miss_builder)

**Comment by yvaucher** [comment]
discussed here: https://github.com/OCA/sale-workflow/pull/54#discussion_r38218235

**Pull request merged**
