### PR TITLE
add: tool to configure travis for an OCA repo

### PR DESCRIPTION
**Pull request by sbidoul**
For now, set 3 variables required by https://github.com/OCA/maintainer-quality-tools/pull/556

### CODE REVIEW

**Comment by sbidoul** [comment]
@pedrobaeza have you seen this one? Don't forget to run it on new repos.

About travis-ci.com, I suggest we stay on travis-ci.org until travis migrates everything at once. Otherwise we'll have additional difficulties to maintain both.

**Comment by pedrobaeza** [comment]
No, I didn't, but this is for travis-ci.org, and I don't want that new repos stay on the old infrastructure, which is more complicated to setup and it's already deprecated. Please update for the new infrastructure.

**Comment by sbidoul** [comment]
Problem is I have no way to know which repo is on which travis.

In the meantime, don't forget to add the `GITHUB_*` variables in the new repos.

**Comment by sbidoul** [comment]
I think we must stay on one travis infrastructure until travis has a proper way to migrate all projects at once, and they are not ready yet.

**Comment by pedrobaeza** [comment]
Is this valid for travis-ci.com?

**Comment by sbidoul** [comment]
I'm afraid it is not. :crying_cat_face:

**Comment by pedrobaeza** [comment]
Oh, what a pity. Well, if you want, we can split the work of changing the token. Please mail me with the details and I'll do for a bunch of them.

**Pull request merged**
