### PR TITLE
Change docutils version and move to GitHub actions

### PR DESCRIPTION
**Pull request by sbidoul**
docutils 0.15.1-post1 has installation issues with pip.
see https://github.com/pypa/pip/issues/9203#issuecomment-740718379

Note: a future pip version may support this again. But we need to unblock our CI now.

Also, if we merge this, the next time we deploy oca-github-bot, it will regenerate all static/description/index.html which will fill the travis build on all branches, and publish a new version of all addons to PyPI.

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Can this be launched with `[ci skip]` for the changes for not launching Travis builds?

**Comment by sbidoul** [comment]
I'll think about something before updating the bot. We have no choice but to merge this. 

Now, we need the pr to oca-addons-repo-template to update the pre-commit config, then deploy to all repos.

**Comment by sbidoul** [comment]
aaand... this repo is now travis-free. 199 to go.

**Comment by pedrobaeza** [comment]
Let's share the duty between CIs! Thanks for all the hard work.

**Comment by dreispt** [comment]
Do we have an ETA for deployment? Thanks!

**Comment by sbidoul** [comment]
@sbidoul ETA "is as soon as I can" :)  https://github.com/OCA/oca-addons-repo-template/pull/44#issuecomment-743046947

**Pull request merged**
