### PR TITLE
readme generator: ignore empty fragments

### PR DESCRIPTION
**Pull request by sbidoul**
As well as auto add missing newline at eof, to avoid
rst syntax errors.

### CODE REVIEW

**Comment by sbidoul** [comment]
@lreficent this should fix the build for mrp_warehouse_calendar.

**Comment by pedrobaeza** [comment]
Taking the occasion for the change, maybe you can remove trailing whitespaces that are generated (for example, on the badges line).

**Comment by sbidoul** [comment]
> remove trailing whitespaces

Not so easy. Why is it a problem?

**Comment by pedrobaeza** [comment]
Well, it's to conform with most of the general linters and diff viewers showing that trailing whitespace.

**Comment by sbidoul** [comment]
Well, afaik the rst checker do not complain. So I'll see what I can do, low priority, not for this PR.

**Comment by pedrobaeza** [comment]
OK

**Pull request merged**
