### PR TITLE
Reduce license headers a bit more.

### PR DESCRIPTION
**Pull request by Yajo**
In JS and CSS files, we save a line, in all others we save 5 chars.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by elicoidal** [comment]
:+1:

**Comment by lmignon** [comment]
:+1:

**Comment by pedrobaeza** [comment]
@Yajo, I'm now seeing that we should point to http://www.gnu.org/licenses/agpl-3.0, not http://www.gnu.org/licenses/agpl, because if some day, there's a new AGPL version, the link won't be the correct.

**Pull request merged**
