### PR TITLE
[IMP] oca-autopep8: Change coding or insert `# coding: utf-8` comment

### PR DESCRIPTION
**Pull request by moylop260**

### CODE REVIEW

**Comment by gurneyalex** [comment]
:+1:

**Comment by StefanRijnhart** [comment]
Signalling a missing coding comment seems good to me, but should we not be agnostic to the exact format of the coding comment, as is https://www.python.org/dev/peps/pep-0263/?

**Comment by yvaucher** [comment]
:+1: 

(needs a rebase)

**Comment by pedrobaeza** [comment]
Is this still applying?

**Pull request closed without merging**
