### PR TITLE
[FIX] gen_addon_readme.template: language typo in readme

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Selection_693

### CODE REVIEW

**Review by norlinhenrik — APPROVED** [review]
[This link](https://jakubmarian.com/help-do-vs-help-to-do-vs-help-doing-in-english/) confirms that "help us to smash" is correct English, but "help us smashing" is not.

**Review by pedrobaeza — APPROVED** [review]
But the CI should be fixed.

**Comment by MiquelRForgeFlow** [comment]
@sbidoul how to fix ci?

**Comment by sbidoul** [comment]
@MiquelRForgeFlow I don't have a definitive solution for this yet. I'll try to consolidate the options in a dedicated issue so we can discuss on something concrete and complete.

**Comment by simahawk** [comment]
still an issue?

**Pull request merged**
