### PR TITLE
[ADD] New tool: oca-port

### PR DESCRIPTION
**Pull request by sebalix**
Tool helping to port an addon or missing commits of an addon from one branch to another.

### /!\ It requires Python 3.8. /!\

If the addon does not exist on the target branch, it will assist the user in the migration, following the OCA migration guide.

If the addon already exists on the target branch, it will retrieve missing commits to port. If a Pull Request exists for a missing commit, it will be ported with all its commits if they were not yet (fully) ported.

To check if an addon could be migrated or to get eligible commits to port:

    $ export GITHUB_TOKEN=<token>
    $ oca-port 13.0 14.0 shopfloor --verbose

To effectively migrate the addon or port its commits, use the `--fork` option:

    $ oca-port 13.0 14.0 shopfloor --fork camptocamp

Migration of addon
------------------

The tool follows the usual OCA migration guide to port commits of an addon, and will invite the user to fullfill the mentionned steps that can't be performed automatically.

**Output example:**
image

Port of commits/Pull Requests
-----------------------------

The tool will ask the user if he wants to open draft pull requests against the upstream repository.

If there are several Pull Requests to port, it will ask the user if he wants to base the next PR on the previous one, allowing the user to cumulate ported PRs in one branch and creating a draft PR against the upstream repository with all of them.

**Output example (with --verbose):**
oca_port_pr_verbose

**Some details:**
- commits history has to be preserved to get this tool working properly: commits equality is checked against a list of attributes like the author name/email, the authored utc datetime, the message... but not the SHA as it changes from one branch to another (so if a ported commit has been amended to change a bit the message, the commit will be considered as not ported, generating false positive)
- merge commit and translations ones are skipped (checking the commit message/author)
- we could have an original commit updating two addons `A` and `B`, and an existing ported commit done in the past through `git format-patch` only for one of the addons e.g. `A`, so the commit will still be considered as eligible to be ported by this tool. If two ported commits exist (each updating one addon, `A` then `B`), the commit will then be considered as already ported
- port is performed with `git format-patch`, if a conflict appears, the process will wait the user to resolve it before continuing the cherry-pick, and so on.
- GitHub token should be set in the `GITHUB_TOKEN` env var

====
It is still a draft, for now I only tested it on `OCA/wms` on a bunch of addons.

**TODO:**
- [x] Propose to open draft PR once the local branch is pushed on the fork
- [x] If the created local branch didn't change after the cherry-pick operations (same underlying sha), don't propose to push & create PR
- [x] Use `git format-patch` instead of `git cherry-pick` to port only changes of relevant addons to avoid to much conflicts if a commit has already been ported partially?
- [ ] Check if an open PR exists and propose the user to review it instead of creating a new one
- [x] <s>Take into account renamed module (a `=>` is used in the list of changed files in commit data, currently they are skipped)</s> Already supported, example [here](https://github.com/OCA/wms/pull/273)
- [ ] Check if it could be integrated to https://github.com/OCA/odoo-module-migrator/ to get only one tool to migrate and maintain modules OR get them complementary
- [x] Improve readability using colors
- [ ] If the module is not ported on the target branch (doesn't exist <s>or `"installable": False`</s>):
    - [x] do not ask the user to port each PR one by one but port **all** their commits directly in a new local branch `14.0-mig-$MODULE` (thanks @simahawk for the idea!), following the usual [migration guide ](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0#technical-method-to-migrate-a-module-from-130-to-140-branch) (so do not skip translation commits etc)
    - [x] and then rename the tool `oca-port` as it's not anymore a tool to port only PRs but entire module as well.
    - [ ] check if an existing PR exists and invite the user to check/review it instead
    - [ ] analyse the addon dependencies and display a warning if they are not all available
- [ ] add an option `--dev-branch` to work on the specified branch instead of `to_branch` (default)

### CODE REVIEW

**Comment by rousseldenis** [comment]
Great!

**Comment by sebalix** [comment]
Live test on `OCA/server-backend` for `base_user_role` module: https://github.com/OCA/server-backend/pull/130

**Comment by sebalix** [comment]
Some PRs generated: https://github.com/OCA/wms/pulls?q=is%3Apr+is%3Aopen+oca-port-pr

**Comment by rousseldenis** [comment]
@sebalix

In some local git configurations, origin is not configured as OCA (changed easily of course).

But shouldn't be good  to have also both remotes as argument ?

**Comment by rousseldenis** [comment]
And ten millions dollars question, shouldn't it be great to select PRs to port with a choice in case of multiple ?

**Comment by rousseldenis** [comment]
Tested there : https://github.com/OCA/search-engine/pull/98

Seems good for me

**Comment by sebalix** [comment]
@rousseldenis we can change the OCA remote with the `--upstream` option.
The tricky thing about the fork is, to not have a lot of options, I stuck to the idea "local remote name == fork org name", maybe I should change that and add an option to separate this.

About porting several PRs at the same time, I'm thinking about it. Often, one PR depends on a previous one (that's why the list of PRs are sorted by merge date), and I was thinking about proposing to the user to base the next PR on the branch of the last ported one, or make it by default... I really don't know how to handle that. It is difficult to know if a PR really depends on a previous one to avoid merge conflicts, and sometime PRs could be merged independently so introducing a dependency between them will just make more noise.

**Comment by simahawk** [comment]
1st of all: this feature is amazing. Thanks!

My POV (as we discussed together): we should improve it to make it THE module migrator and fwd/back porter. I would:

1. rename it to `oca-port` (is not just about a bunch of PRs)
2. rip out of odoo-module-migrator everything but the tasks for making modules compat w/ the target version
3. run odoo-module-migrator at the end of the process

As we discussed, using it for migration would require "only" to:

1. auto-detect that the module is new (via checking the diff type)
2. based on this use the same for all PRs and not ask to port each PR singularly
3. use one single branch (called *-mig-* instead of `*-pr-$number-*`

Finally one more feature could be: finding pending PRs before migrating. Meaning that the tool could say "hey, there's a pending PR that you could help review/merge that could be included in the migration". Or something like that.
This way we would avoid the typical request like "ah, there's this fix/imp that would be nice to include can you cherry-pick?"
For version 2.0 maybe... :smile:

**Comment by pedrobaeza** [comment]
Thanks for this tool. Note that the guideline for the PR title is 

`[<version>][<type>] <module>: <short explanation>`

Example: `[14.0][FIX] date_range: Fix search`

Thus, several comments about the PR title format.

- Putting `[13.0->14.0]` at the beginning, changes this guideline. Put only the target branch.
- The same happens with `[oca-port-pr-#171]`, that should be out IMO.

I think both information should be on the main comment instead of being part of the title. We can suffix (or prefix) the PR with a similar formula like Odoo does, putting something short like `(FW)`.

**Comment by sebalix** [comment]
@pedrobaeza is a PR title `[14.0][PORT] {addon}: {title}` acceptable? As it can be difficult to guess what the original PR is about, unless by parsing original PR title but it begins to be quite complex. Or `[14.0][FW] {addon}: {title}`?

**Comment by pedrobaeza** [comment]
If you are parsing the module, why is it more difficult to parse the rest of the previous title?

Anyways, in such case, I think it becomes more acceptable this mask: `[14.0][FW] <title>`, so the original PR title being `[12.0][FIX] date_range: Fix search`, and fw-port it to 14.0, will result in `[14.0][FW] [12.0][FIX] date_range: Fix search`, and we have both source and target branch, and let the contributor to set the rest of the title more freely.

**Comment by sebalix** [comment]
Because it's easier to wipe out things between brackets and version numbers from the original title, then adding our own suffixes afterward :)
But a possibility is to only remove version numbers from the original PR title (e.g. `13.0` or `[13.0]`) and keep all the rest, that means the new PR title could be:
- `[14.0][MIG] ...`
- `[14.0] mig ...` (like there: https://github.com/OCA/stock-logistics-workflow/pull/861)
- `[14.0] ...` (without any suffix)
And up the the user or PSC members to rename the PR afterwards.

**Comment by pedrobaeza** [comment]
I think it can be valuable to keep whole title for knowing the source, as you can do a patch in 12.0, and want to fw-port it to 13.0 and 14.0 (well, `black` will provoke incorrect PR for sure in this case, but I am exposing it as example). I let you the final word, as you are the one doing the work.

Other things that come to my mind now that I have dived a bit more in the PR:

- On the command line itself, don't you think it's better to do have `oca-port-pr 13.0 14.0 --addon shopfloor_packing_info`. We lose the possibility of altering order, but we gain on number of characters to type.
- If there's any conflict applying the patch, whole process can be resumed by any way?
- Isn't overlapping a bit with oca-module-migrator commit extraction part (saving the translation and administrative commits part)?
- Other option can be to integrate it on ocabot for launching the fw-ports from a comment in the original PR:

  `ocabot fw-port up-to 13.0`

  Cons of this:

  * PRs will be created under OCA branches with no possibility of changing them.
  * Conflicts may arise with no possibility of amending them without forking.

**Comment by sebalix** [comment]
@pedrobaeza 

> I think it can be valuable to keep whole title for knowing the source, as you can do a patch in 12.0, and want to fw-port it to 13.0 and 14.0 (well, `black` will provoke incorrect PR for sure in this case, but I am exposing it as example). I let you the final word, as you are the one doing the work.

We could do that indeed. It begins to be tricky if we want to forward port a PR on the two next versions (and we start on the previous one to make the next, so the title will be very long), but I think it is rare and we could still rename the PR afterwards. I'm also looking for existing PR created by this tool based on its name, but it seems GH is keeping previous PR values somewhere because I could still find the PR through GH API even with its old name. So let's do this simple for the moment with `[14.0][FW] {original_title}`.

> * On the command line itself, don't you think it's better to do have `oca-port-pr 13.0 14.0 --addon shopfloor_packing_info`. We lose the possibility of altering order, but we gain on number of characters to type.

Good idea, I'll do that.

> * If there's any conflict applying the patch, whole process can be resumed by any way?

If a conflict appears, the process will wait (as shown in the output example in the PR description), the user will have to resolve the conflict the normal way (finishing the resolution either with a `git am --continue` or `git am --skip`) and resume the process.
If he left the process then no, there is at the moment no option to restart the work on a given PR.

> * Isn't overlapping a bit with oca-module-migrator commit extraction part (saving the translation and administrative commits part)?

We discussed about that with @simahawk (see its comment above), later this tool could replace `odoo-module-migrator` for the part related to `git format-patch`, but it would still be needed then to adapt the code to the targeted branch, at the end they will be complementary.

> * Other option can be to integrate it on ocabot for launching the fw-ports from a comment in the original PR:
>   `ocabot fw-port up-to 13.0`
>   Cons of this:
>   
>   * PRs will be created under OCA branches with no possibility of changing them.
>   * Conflicts may arise with no possibility of amending them without forking.

Indeed, @gurneyalex whispers me this idea some weeks ago. Good catch about access rights, and sometime we have to resolve small conflicts (because of pre-commit changes for instance) so it's not easy to get a complete automatic flow here.

**Comment by sebalix** [comment]
Last feature: `Use the previous PR #126 branch as base?`
```shell
$ oca-port-pr 13.0 14.0 --addon stock_available_to_promise_release --fork camptocampFetch origin/13.0 from git://github.com/OCA/wms.git
Fetch origin/14.0 from git://github.com/OCA/wms.git

7 pull request(s) related to 'stock_available_to_promise_release' to port from origin/13.0 to origin/14.0

- PR #104 (https://github.com/OCA/wms/pull/104) [FIX] shopfloor: cluster picking, remove unavailable picking from validated batch:
	By sebalix, merged at 2021-01-13T09:10:57Z
	=> Not ported: ['stock_available_to_promise_release']
	=> 1 commit(s) not (fully) ported
- PR #94 (https://github.com/OCA/wms/pull/94) [13.0][FIX] 'Release ready' based on the shipping policy of the order:
	By sebalix, merged at 2021-01-13T11:53:40Z
	=> Not ported: ['stock_available_to_promise_release', 'sale_stock_available_to_promise_release']
	=> 1 commit(s) not (fully) ported
- PR #116 (https://github.com/OCA/wms/pull/116) [13.0] stock_available_to_promise_release: Change test case helper methods as classmethod:
	By guewen, merged at 2021-01-14T14:08:03Z
	=> Not ported: ['stock_available_to_promise_release']
	=> 1 commit(s) not (fully) ported
- PR #106 (https://github.com/OCA/wms/pull/106) stock_available_to_promise_release: Fix quantity available to promise of released moves:
	By jbaudoux, merged at 2021-01-14T14:40:11Z
	=> Not ported: ['stock_available_to_promise_release']
	=> 2 commit(s) not (fully) ported
- PR #126 (https://github.com/OCA/wms/pull/126) [13.0] stock_available_to_promise_release: Fix horizon - count released move outside horizon:
	By jbaudoux, merged at 2021-01-21T12:48:02Z
	=> Not ported: ['stock_available_to_promise_release']
	=> 2 commit(s) not (fully) ported
- PR #173 (https://github.com/OCA/wms/pull/173) [13.0] Add shopfloor_workstation + sync w/ OCA/oca-addons-repo-template:
	By simahawk, merged at 2021-02-12T01:48:18Z
	=> Not ported: ['CONTRIBUTING.md', '.pylintrc-mandatory', 'README.md', 'stock_move_source_relocate_dynamic_routing', '.travis.yml', 'stock_reception_screen', 'stock_available_to_promise_release', 'oca_dependencies.txt', 'sale_stock_available_to_promise_release', '.prettierrc.yml', 'requirements.txt', '.pre-commit-config.yaml', '.github', '.copier-answers.yml', 'LICENSE', '.pylintrc', '.gitignore', 'shopfloor_workstation', 'setup']
	=> 4 commit(s) not (fully) ported
- PR #174 (https://github.com/OCA/wms/pull/174) [13.0] stock_available_to_promise_release: Fix release of operation containing canceled moves:
	By sebalix, merged at 2021-02-17T16:31:31Z
	=> Not ported: ['stock_available_to_promise_release']
	=> 2 commit(s) not (fully) ported

- Port PR #104 (https://github.com/OCA/wms/pull/104) [FIX] shopfloor: cluster picking, remove unavailable picking from validated batch...
	Port it? [y/N]: y
	Create branch oca-port-pr-104-from-13.0-to-14.0 from origin/14.0...
		Apply ee928218552708328cd4bf0026045de4d25abf5f [FIX] stock_available_to_promise_release: fix flappy test...
	Push branch 'oca-port-pr-104-from-13.0-to-14.0' to remote 'camptocamp'? [y/N]: 
- Port PR #94 (https://github.com/OCA/wms/pull/94) [13.0][FIX] 'Release ready' based on the shipping policy of the order...
	Port it? [y/N]: y
	Use the previous PR #104 branch as base? [y/N]: y
	Create branch oca-port-pr-94-from-13.0-to-14.0 from oca-port-pr-104-from-13.0-to-14.0...
		Apply 5342da2d84b7d487815611e423be2a10e3280b94 [FIX] 'Release ready' based on the shipping policy of the order...
	Push branch 'oca-port-pr-94-from-13.0-to-14.0' to remote 'camptocamp'? [y/N]: 
- Port PR #116 (https://github.com/OCA/wms/pull/116) [13.0] stock_available_to_promise_release: Change test case helper methods as classmethod...
	Port it? [y/N]: y
	Use the previous PR #94 branch as base? [y/N]: y
	Create branch oca-port-pr-116-from-13.0-to-14.0 from oca-port-pr-94-from-13.0-to-14.0...
		Apply 6c7587a4188a4de24216110c19027c81c22d6a0d Change test case helper methods as classmethod...
	Push branch 'oca-port-pr-116-from-13.0-to-14.0' to remote 'camptocamp'? [y/N]: 
- Port PR #106 (https://github.com/OCA/wms/pull/106) stock_available_to_promise_release: Fix quantity available to promise of released moves...
	Port it? [y/N]: y
	Use the previous PR #116 branch as base? [y/N]: y
	Create branch oca-port-pr-106-from-13.0-to-14.0 from oca-port-pr-116-from-13.0-to-14.0...
		Apply 9ac87637c17d0291862027000e3124fbe8b93a01 stock_available_to_promise_release: Fix quantity available to promise of released moves...
		Apply 0c57c0fc2d405b332bfc38affd557d3309bf5776 stock_available_to_promise_release: Fix moves for which available to promise is computed...
	Push branch 'oca-port-pr-106-from-13.0-to-14.0' to remote 'camptocamp'? [y/N]: 
- Port PR #126 (https://github.com/OCA/wms/pull/126) [13.0] stock_available_to_promise_release: Fix horizon - count released move outside horizon...
	Port it? [y/N]: y
	Use the previous PR #106 branch as base? [y/N]: y
	Create branch oca-port-pr-126-from-13.0-to-14.0 from oca-port-pr-106-from-13.0-to-14.0...
		Apply bc0d4dd7173acbed823fac71e93a9c43ba27e5f5 stock_available_to_promise_release: when a move is released, it must be counted in the stock previously promised even when it is outside horizon...
		Apply dbb9d7c6c1494d2b58ac55cacd755f728b3d81d4 Fix update of quantity in tests...
	Push branch 'oca-port-pr-126-from-13.0-to-14.0' to remote 'camptocamp'? [y/N]: 
- Port PR #173 (https://github.com/OCA/wms/pull/173) [13.0] Add shopfloor_workstation + sync w/ OCA/oca-addons-repo-template...
	Port it? [y/N]: 
- Port PR #174 (https://github.com/OCA/wms/pull/174) [13.0] stock_available_to_promise_release: Fix release of operation containing canceled moves...
	Port it? [y/N]: y
	Branch oca-port-pr-174-from-13.0-to-14.0 already exists, recreate it? 
	(WARNING: you will lose the existing branch) [y/N]: y
	Use the previous PR #126 branch as base? [y/N]: y
	Create branch oca-port-pr-174-from-13.0-to-14.0 from oca-port-pr-126-from-13.0-to-14.0...
		Apply d2bd0b89535e1d287fe6d0073029d416bb1aab85 Fix release of operation containing canceled moves...
		Apply 7c95bdca1272b8c88c1044b9eb28dca93279c093 Fix release of operation containing canceled moves (test)...
	🎉 Last PR processed! 🎉
	Push branch 'oca-port-pr-174-from-13.0-to-14.0' to remote 'camptocamp'? [y/N]: y
	PR(s) ported locally: #104, #94, #116, #106, #126, #174
	Create a draft PR from 'oca-port-pr-174-from-13.0-to-14.0' to '14.0' against OCA/wms? [y/N]: y
		PR created => https://github.com/OCA/wms/pull/270
```

**Comment by sebalix** [comment]
Added some fancy colors to the output, PR description example updated ⬆️

**Comment by sebalix** [comment]
Tool renamed `oca-port` as it now handles the migration of an addon if this one hasn't been found in the target branch. Description of the PR udpated ⬆️

**Comment by sebalix** [comment]
Fixed and improved the output when dealing with commits without PR:
image

**Comment by sebalix** [comment]
Commit https://github.com/OCA/maintainer-tools/pull/504/commits/581755f4d7003702f58d3c8a7fd561bc173c762b will check if there are commits to port after the migration of a module, this allows to also port changes done in neighboring addons in the original commit that were skipped by `git format-patch` (which is focused only on the addon we want to migrate).
Of course we could also try to do a `git format-patch` on all related addons/files but I thought that it could generates more conflicts than necessary. Launching the missing commits analysis right after a module migration provides also to the user an interactive way to not port missing commits because they are not relevant.
The following PR has been done with this feature: https://github.com/OCA/wms/pull/281

**Comment by simahawk** [comment]
Testing the blacklist improvement: works like a charm.
```
$ oca-port 13.0 14.0 base_ubl --verbose --upstream-org OCA --upstream OCA --fork camptocamp
Fetch OCA/13.0 from git@github.com:OCA/edi.git
Fetch OCA/14.0 from git@github.com:OCA/edi.git
base_ubl already exists on 14.0, checking PRs to port...
PR #236 blacklisted
PR #277 blacklisted
PR #421 blacklisted
PR #384 blacklisted
1 pull request(s) related to 'base_ubl' to port from OCA/13.0 to OCA/14.0

1) PR #423 (https://github.com/OCA/edi/pull/423) [13.0][IMP] base_ubl: add customer as an argument in _ubl_add_item method:
        By FerranCforgeFlow, merged at 2021-08-09T13:16:57Z
        => Updates: base_ubl
        => Not ported: base_ubl
        => 1 commit(s) not (fully) ported
                2256a71b [13.0][FIX] base_ubl: add argument in _ubl_add_item and fixed _ubl_add_supplier_party and _ubl_add_customer_party

- Port PR #423 (https://github.com/OCA/edi/pull/423) [13.0][IMP] base_ubl: add customer as an argument in _ubl_add_item method...
        Port it? [y/N]: N
        Remember this choice? [y/N]: 
```
Super cool! :raised_hands:

**Review by simahawk — APPROVED** [review]
I have no time for tech review now, but the functional review is definitely :+1: 

@sebalix one last small change request: can we move the PR URL on the next line? Seems more readable IMO.

**Comment by simahawk** [comment]
Regarding `./.oca-port.json` and

> Being able to commit this file would be nice in the future (if this tool is merged), is there a blocking point to do that?

Potentially, it's a good thing to do. Because then everyone can share the same status. At the same time I fear we'll end up w/ tons of conflicts. How would you manage that?

**Comment by sebalix** [comment]
@simahawk a solution is to instead have a folder `./.oca-port/` with one file per addon in it:

```
.oca-port
├── ADDON_1.json
└── ADDON_2.json
```
Another note regarding this file, I'll only keep the targeted version, if the fileis commited then no need to keep the source version (the source version is the branch where the file is committed).

> @sebalix one last small change request: can we move the PR URL on the next line? Seems more readable IMO.
No problem

**Comment by simahawk** [comment]
@sebalix the problem is only mitigated then. What if we have:

```
.oca-port.d
-- addon1
---- blacklisted
------ 1.json
------ 2.json
```
(or skip the blacklisted folder and prefix filename w/ `bl`)
Each file then contains details (eg: who skipped it and when) and an explanation of why the PR has been skipped.
These files can even be pure `.txt` which just the explanation and just leave to the git history the role of finding the author.
This way, each PR is independent.

**Comment by sebalix** [comment]
@simahawk I was supposing that a developer who run `oca-port` on a given addon will be able to decide for all PRs if they should be ported or not, not having someone blacklisting one PR, and someone else blacklisting another PR at the same time. If you think it is a scenario that could happen then yes, we could have 1 file / PR like you suggest.

**Comment by simahawk** [comment]
@sbidoul @pedrobaeza @rousseldenis can you give feedback on this?
We are using it since months and sounds solid enough. 
There's is also the discussion regarding keeping on the repo the blacklist tracking so that we can share what's worth to keep and what's not. Of course this is something for the future and is not a blocker for the current PR because is not changing anything in this sense.

CC @OCA/community-maintainers

**Comment by pedrobaeza** [comment]
If you think it's OK, go ahead with the merge.

**Comment by sbidoul** [comment]
I've not had a chance to try it but I like the concept.
Have you considered creating a standalone project for it ? Because maintainer-tools is a bit of a mess...

**Comment by simahawk** [comment]
> I've not had a chance to try it but I like the concept. Have you considered creating a standalone project for it ? Because maintainer-tools is a bit of a mess...

TBH I'd prefer to have a separate project. Then MT could be just a bundle of them w/ some default conf maybe.
@sebalix what do you think?

**Comment by sebalix** [comment]
@simahawk I agree, it'll also helps to show a quick user documentation in a README like the description of this PR.

**Comment by simahawk** [comment]
> @simahawk I agree, it'll also helps to show a quick user documentation in a README like the description of this PR.

cool, I'll setup a new repo when you are ready

**Comment by pedrobaeza** [comment]
The option to include this in module-migrator has been discarded?

**Comment by dreispt** [comment]
Maybe we need  "OCA/contributor-tools" ?

**Comment by simahawk** [comment]
> The option to include this in module-migrator has been discarded?

What this tool does is a different work. It's not migrating modules where "migrating" means "adapt the code to a newer of older version of Odoo". It eases back/fwd porting of PRs and commits.

I would keep it separated and we could integrate the migrator as a feature later that can be installed optionally by the user (`pip install oca-port[migrator]`).

**Comment by hparfr** [comment]
Thanks for this tool @sebalix.

I have tested it against field-service for porting merged PR.
`oca-port 12.0 14.0 fieldservice --verbose --fork akretion`

Perf:
More progression feedback can be good. It took 10min to run on my machine the first time. Then I got API limit issues (because I didn't properly pass github token).

BranchesDiff() takes ~25seconds before the first request.

Issues:

* False positives: 40ish ports were proposed to be done but were already merged. The blacklist was then a lifesaver.
* With all ports created with this tool, I always had merge conflicts. — do not know if it was expected.
* At the end of some ports, I was unable to continue because of trackeback:  `RuntimeError: {"message":"Validation Failed","errors":[{"resource":"PullRequest","code":"custom","message":"No commits between OCA:14.0 and akretion:oca-port-pr-850-from-12.0-to-14.0"}],"documentation_url":"https://docs.github.com/rest/reference/pulls#create-a-pull-request"}` or   `stderr: 'fatal: previous rebase directory .git/rebase-apply still exists but mbox given.'`  or `stderr: 'fatal: Resolve operation not in progress, we are not resuming.'`. — Just had to go back to a stable git state, then re-run `oca-port`
* When re-run oca-port, already port done by me some minutes ago, pushed but not merged are suggested. — may be skip them if a branch named by oca-port already exists on the remote or local.

Features I miss be able to target a precise (known) PR 

> Note that the guideline for the PR title is
> [\<version>][\<type>] \<module>: \<short explanation>
> Example: [14.0][FIX] date_range: Fix search
> The same happens with [oca-port-pr-#171], that should be out IMO.
> I think both information should be on the main comment instead of being part of the title.

Do not agree: having the original PR number in the name can help to track the progression.
ie:  ` [14.0][FW] [12.0][FIX] date_range: Fix search  #171 `


> Being able to commit this file would be nice in the future (if this tool is merged), is there a blocking point to do that? 

There a distinction between (shared knowledge): the PR should not be merged (because it's false positive, a dead feature, not needed anymore...) and (local) I do not want to work on this PR now and do not want to be asked again next time.


Conclusion: Really nice tool, I think it's good enough yet to be merged (or put on his own repo).

**Review by hparfr — APPROVED** [review]

**Comment by sebalix** [comment]
@hparfr thank you for your feedback!

> Perf:
> More progression feedback can be good. It took 10min to run on my machine the first time. Then I got API limit issues (because I didn't properly pass github token).
> 
> BranchesDiff() takes ~25seconds before the first request.

10min, it's quite a lot even with a lot of commits to check :thinking: But yes it is sometimes a bit slow, I tried to reduce the time needed (even by switching from `GitPython` to `pygit2` but it was worse!). But there is space for improvements like putting some cache on disk.

> With all ports created with this tool, I always had merge conflicts. — do not know if it was expected.

It is expected, especially if the code base has changed a bit because of migration commits or, more often, new format rules with `pre-commit`.

> At the end of some ports, I was unable to continue because of trackeback: 

Never encountered this one... or maybe because you didn't execute `git am --continue` or `git am --skip` once you resolved the conflicts, letting the repository in a bad state for the next commit to port?

> When re-run oca-port, already port done by me some minutes ago, pushed but not merged are suggested. — may be skip them if a branch named by oca-port already exists on the remote or local.

Good idea, the tool should ask the user if they want to resume from there is there is a branch.

> Features I miss be able to target a precise (known) PR

I miss it too, really a nice-to-have for the next time.

> There a distinction between (shared knowledge): the PR should not be merged (because it's false positive, a dead feature, not needed anymore...) and (local) I do not want to work on this PR now and do not want to be asked again next time.
Indeed, so maybe add a comment when blacklisting a PR, and if we want to blacklist it locally, store this in a file that is `.gitignored`.

**Comment by simahawk** [comment]
Example of blacklisting to be shared https://github.com/OCA/edi/pull/513

**Review by etobella — APPROVED** [review]
Tested locally. Seems amazing!!!

**Comment by bosd** [comment]
Looks like an amazing tool!!!
However, encountered a 
``` Error: changes not committed detected in this repository.```
How to solve this?

**Review by rousseldenis — APPROVED** [review]
@sebalix Is it scheduled to merge this ?

**Comment by rousseldenis** [comment]
> > Is it scheduled to merge this
> 
> I think the plan was to move it to its own repo.

Let's go ! :smiley:

**Comment by simahawk** [comment]
Hi all, thanks for testing/reviewing :pray: 
We are super busy w/ some go lives :sweat_smile: We'll get back to this ASAP :wink:

**Comment by simahawk** [comment]
@sebalix better late than never https://github.com/OCA/oca-port :wink:

**Comment by sebalix** [comment]
This tool is now hosted on https://github.com/OCA/oca-port/, I'm closing this PR.

**Pull request closed without merging**
