### PR TITLE
[REF] .travis.yml: Use distribution precise linux 12.04

### PR DESCRIPTION
**Pull request by moylop260**
In order to fix https://github.com/OCA/maintainer-tools/pull/289#issuecomment-328924874

### CODE REVIEW

**Comment by lasley** [comment]
Isn't this just due to a lack of `python-dev` headers? `build_c` is the CPython builder module, which I believe is included in `python-dev`.

**Comment by moylop260** [comment]
I'm agree
Currently the new image 14.04 has 19 issues:
 - https://github.com/travis-ci/travis-ci/labels/2017-Q3-trusty-env-update

[2 related with python-dev](https://github.com/travis-ci/travis-ci/issues?utf8=%E2%9C%93&q=is%3Aopen%20label%3A2017-Q3-trusty-env-update%20python-dev) but is WIP.

What is the best solution now?

Wait for fix? (But what about current PRs like as https://github.com/OCA/maintainer-tools/pull/289)

**Comment by lasley** [comment]
@moylop260 - I just presented a solution in #292 that gets us a green. Is there something else I need to be looking for other than a green here?

**Comment by lasley** [comment]
Well crap maybe not - I got a green on one then submitted the PR and it went red 😦

**Comment by lasley** [comment]
@moylop260 - I can't replicate this problem in any of my dev machines. Do we know how to launch a Travis environment locally, or is can we only test by pushing to Travis?

**Comment by moylop260** [comment]
The images for old dist was hosted here:
https://quay.io/organization/travisci

But new ones I didn't see them
Maybe now the my are not publishing them

**Pull request merged**
