### PR TITLE
Convert readme fragment examples to markdown

### PR DESCRIPTION
**Pull request by sbidoul**

### CODE REVIEW

**Comment by sbidoul** [comment]
@TumbaoJu

**Comment by TumbaoJu** [comment]
> @TumbaoJu

Thank you!

**Comment by francesco-ooops** [comment]
@sbidoul thanks! who can review this?

**Comment by sbidoul** [comment]
@francesco-ooops This does not necessarily need review. I propose to wait until the documentation working group has communicated about the markdown support before officially changing the template.

**Comment by TumbaoJu** [comment]
@sbidoul We want to propose changes in the description that is why we were waiting for this PR to be merged to propose thoses changes and use markdown to do it ;)
@francesco-ooops FYI

**Comment by sbidoul** [comment]
Ok, I'm happy to merge. But maybe we then should not wait until OCA Days to communicate, as some devs may be surprised by the change.

**Comment by TumbaoJu** [comment]
@sbidoul : We are already prepared the communication.  I will sent it to you for revision but yes, we plan to send it in the next weeks

**Pull request merged**
