### PR TITLE
Odoo guideline is a tests direcory for py and yml

### PR DESCRIPTION
**Pull request by dreispt**
Fix tests directory guideline, following discussion on #201

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by moylop260** [comment]
Is this really valid in the practice?
I saw test and tests folders from master version of odoo/odoo yet.

**Comment by moylop260** [comment]
I mean, If you run:

`find addons/*/test/ -name *.yml | wc -l`
Result: 57

`find addons/*/tests/ -name *.yml | wc -l`
Result: 1

screen shot 2016-07-07 at 7 35 40 am

**Comment by dreispt** [comment]
@moylop It's in the guidelines.

**Comment by moylop260** [comment]
Could you add a `yml` dummy file in [template/module/tests](https://github.com/OCA/maintainer-tools/tree/master/template/module/tests) please?

**Comment by dreispt** [comment]
@moylop260 I don't see the point. Anyway, if people feel it's necessary in should go in a different PR.

**Comment by moylop260** [comment]
@dreispt Ok, I mean, the point is:

We have https://github.com/OCA/maintainer-tools/tree/master/template/module
screen shot 2016-07-07 at 8 44 58 am

We have the complete tree example
screen shot 2016-07-07 at 8 44 31 am

IMHO If we change the `template/module` we should change the text of the `complete tree` too.
If we change the `complete tree` we should change the `template/module` too.

This point is in order to avoid have a discuss similar to https://github.com/OCA/maintainer-tools/pull/191 in the future, you can see a example where the `template/module` tell us a thing and the contribute's document tell us other thing.

IMHO If we add/change the `yml` file in the contribute's document then we need concordant in the template module yet.

**Comment by dreispt** [comment]
The template module is a just template, not a guideline.
If a guideline is not clear, it should be clarified in the guideline document.
In this case, py are generally considered superior to yml, so I see no point in adding a yml test template.

**Comment by moylop260** [comment]
> In this case, py are generally considered superior to yml, so I see no point in adding a yml test template.

Good point
Thanks for clarify

Maybe our guideline should be not use .yml

**Comment by dreispt** [comment]
> Maybe our guideline should be not use .yml

IMO we should suggest avoiding them, but nor forbid.

**Comment by moylop260** [comment]
👍

**Comment by osvalr** [comment]
:+1:

**Comment by elicoidal** [comment]
:+1:

**Pull request merged**
